/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateResourceTypeAdminConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateResourceTypeAdminConfigRequest{}

// UpdateResourceTypeAdminConfigRequest Admin configuration update for a resource type
type UpdateResourceTypeAdminConfigRequest struct {
	StorageClass         *string           `json:"storageClass,omitempty"`
	Labels               map[string]string `json:"labels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateResourceTypeAdminConfigRequest UpdateResourceTypeAdminConfigRequest

// NewUpdateResourceTypeAdminConfigRequest instantiates a new UpdateResourceTypeAdminConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResourceTypeAdminConfigRequest() *UpdateResourceTypeAdminConfigRequest {
	this := UpdateResourceTypeAdminConfigRequest{}
	return &this
}

// NewUpdateResourceTypeAdminConfigRequestWithDefaults instantiates a new UpdateResourceTypeAdminConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResourceTypeAdminConfigRequestWithDefaults() *UpdateResourceTypeAdminConfigRequest {
	this := UpdateResourceTypeAdminConfigRequest{}
	return &this
}

// GetStorageClass returns the StorageClass field value if set, zero value otherwise.
func (o *UpdateResourceTypeAdminConfigRequest) GetStorageClass() string {
	if o == nil || IsNil(o.StorageClass) {
		var ret string
		return ret
	}
	return *o.StorageClass
}

// GetStorageClassOk returns a tuple with the StorageClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceTypeAdminConfigRequest) GetStorageClassOk() (*string, bool) {
	if o == nil || IsNil(o.StorageClass) {
		return nil, false
	}
	return o.StorageClass, true
}

// HasStorageClass returns a boolean if a field has been set.
func (o *UpdateResourceTypeAdminConfigRequest) HasStorageClass() bool {
	if o != nil && !IsNil(o.StorageClass) {
		return true
	}

	return false
}

// SetStorageClass gets a reference to the given string and assigns it to the StorageClass field.
func (o *UpdateResourceTypeAdminConfigRequest) SetStorageClass(v string) {
	o.StorageClass = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *UpdateResourceTypeAdminConfigRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceTypeAdminConfigRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *UpdateResourceTypeAdminConfigRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *UpdateResourceTypeAdminConfigRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o UpdateResourceTypeAdminConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateResourceTypeAdminConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StorageClass) {
		toSerialize["storageClass"] = o.StorageClass
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateResourceTypeAdminConfigRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateResourceTypeAdminConfigRequest := _UpdateResourceTypeAdminConfigRequest{}

	err = json.Unmarshal(data, &varUpdateResourceTypeAdminConfigRequest)

	if err != nil {
		return err
	}

	*o = UpdateResourceTypeAdminConfigRequest(varUpdateResourceTypeAdminConfigRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "storageClass")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateResourceTypeAdminConfigRequest struct {
	value *UpdateResourceTypeAdminConfigRequest
	isSet bool
}

func (v NullableUpdateResourceTypeAdminConfigRequest) Get() *UpdateResourceTypeAdminConfigRequest {
	return v.value
}

func (v *NullableUpdateResourceTypeAdminConfigRequest) Set(val *UpdateResourceTypeAdminConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResourceTypeAdminConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResourceTypeAdminConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResourceTypeAdminConfigRequest(val *UpdateResourceTypeAdminConfigRequest) *NullableUpdateResourceTypeAdminConfigRequest {
	return &NullableUpdateResourceTypeAdminConfigRequest{value: val, isSet: true}
}

func (v NullableUpdateResourceTypeAdminConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResourceTypeAdminConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
