/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateResourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateResourceRequest{}

// UpdateResourceRequest struct for UpdateResourceRequest
type UpdateResourceRequest struct {
	Name *string `json:"name,omitempty"`
	Config map[string]interface{} `json:"config,omitempty"`
	Links []map[string]interface{} `json:"links,omitempty"`
	ConfirmDestructive *bool `json:"confirmDestructive,omitempty"`
}

// NewUpdateResourceRequest instantiates a new UpdateResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResourceRequest() *UpdateResourceRequest {
	this := UpdateResourceRequest{}
	return &this
}

// NewUpdateResourceRequestWithDefaults instantiates a new UpdateResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResourceRequestWithDefaults() *UpdateResourceRequest {
	this := UpdateResourceRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateResourceRequest) SetName(v string) {
	o.Name = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *UpdateResourceRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetLinks() []map[string]interface{} {
	if o == nil || IsNil(o.Links) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetLinksOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []map[string]interface{} and assigns it to the Links field.
func (o *UpdateResourceRequest) SetLinks(v []map[string]interface{}) {
	o.Links = v
}

// GetConfirmDestructive returns the ConfirmDestructive field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetConfirmDestructive() bool {
	if o == nil || IsNil(o.ConfirmDestructive) {
		var ret bool
		return ret
	}
	return *o.ConfirmDestructive
}

// GetConfirmDestructiveOk returns a tuple with the ConfirmDestructive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetConfirmDestructiveOk() (*bool, bool) {
	if o == nil || IsNil(o.ConfirmDestructive) {
		return nil, false
	}
	return o.ConfirmDestructive, true
}

// HasConfirmDestructive returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasConfirmDestructive() bool {
	if o != nil && !IsNil(o.ConfirmDestructive) {
		return true
	}

	return false
}

// SetConfirmDestructive gets a reference to the given bool and assigns it to the ConfirmDestructive field.
func (o *UpdateResourceRequest) SetConfirmDestructive(v bool) {
	o.ConfirmDestructive = &v
}

func (o UpdateResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateResourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.ConfirmDestructive) {
		toSerialize["confirmDestructive"] = o.ConfirmDestructive
	}
	return toSerialize, nil
}

type NullableUpdateResourceRequest struct {
	value *UpdateResourceRequest
	isSet bool
}

func (v NullableUpdateResourceRequest) Get() *UpdateResourceRequest {
	return v.value
}

func (v *NullableUpdateResourceRequest) Set(val *UpdateResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResourceRequest(val *UpdateResourceRequest) *NullableUpdateResourceRequest {
	return &NullableUpdateResourceRequest{value: val, isSet: true}
}

func (v NullableUpdateResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


