/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the ResourceStatusDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceStatusDetail{}

// ResourceStatusDetail struct for ResourceStatusDetail
type ResourceStatusDetail struct {
	Phase                  *string              `json:"phase,omitempty"`
	Message                *string              `json:"message,omitempty"`
	ObservedGeneration     *int64               `json:"observedGeneration,omitempty"`
	Replicas               *ReplicaStatus       `json:"replicas,omitempty"`
	Conditions             []ResourceCondition  `json:"conditions,omitempty"`
	CustomDomains          []CustomDomainStatus `json:"customDomains,omitempty"`
	Links                  []LinkStatus         `json:"links,omitempty"`
	PrimaryDeploymentId    *string              `json:"primaryDeploymentId,omitempty"`
	PrimaryImage           *string              `json:"primaryImage,omitempty"`
	LastDeploymentTime     *time.Time           `json:"lastDeploymentTime,omitempty"`
	LastSyncTime           *time.Time           `json:"lastSyncTime,omitempty"`
	LatestDeploymentId     *string              `json:"latestDeploymentId,omitempty"`
	LatestDeploymentStatus *string              `json:"latestDeploymentStatus,omitempty"`
}

// NewResourceStatusDetail instantiates a new ResourceStatusDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceStatusDetail() *ResourceStatusDetail {
	this := ResourceStatusDetail{}
	return &this
}

// NewResourceStatusDetailWithDefaults instantiates a new ResourceStatusDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceStatusDetailWithDefaults() *ResourceStatusDetail {
	this := ResourceStatusDetail{}
	return &this
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *ResourceStatusDetail) SetPhase(v string) {
	o.Phase = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResourceStatusDetail) SetMessage(v string) {
	o.Message = &v
}

// GetObservedGeneration returns the ObservedGeneration field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetObservedGeneration() int64 {
	if o == nil || IsNil(o.ObservedGeneration) {
		var ret int64
		return ret
	}
	return *o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetObservedGenerationOk() (*int64, bool) {
	if o == nil || IsNil(o.ObservedGeneration) {
		return nil, false
	}
	return o.ObservedGeneration, true
}

// HasObservedGeneration returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasObservedGeneration() bool {
	if o != nil && !IsNil(o.ObservedGeneration) {
		return true
	}

	return false
}

// SetObservedGeneration gets a reference to the given int64 and assigns it to the ObservedGeneration field.
func (o *ResourceStatusDetail) SetObservedGeneration(v int64) {
	o.ObservedGeneration = &v
}

// GetReplicas returns the Replicas field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetReplicas() ReplicaStatus {
	if o == nil || IsNil(o.Replicas) {
		var ret ReplicaStatus
		return ret
	}
	return *o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetReplicasOk() (*ReplicaStatus, bool) {
	if o == nil || IsNil(o.Replicas) {
		return nil, false
	}
	return o.Replicas, true
}

// HasReplicas returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasReplicas() bool {
	if o != nil && !IsNil(o.Replicas) {
		return true
	}

	return false
}

// SetReplicas gets a reference to the given ReplicaStatus and assigns it to the Replicas field.
func (o *ResourceStatusDetail) SetReplicas(v ReplicaStatus) {
	o.Replicas = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetConditions() []ResourceCondition {
	if o == nil || IsNil(o.Conditions) {
		var ret []ResourceCondition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetConditionsOk() ([]ResourceCondition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ResourceCondition and assigns it to the Conditions field.
func (o *ResourceStatusDetail) SetConditions(v []ResourceCondition) {
	o.Conditions = v
}

// GetCustomDomains returns the CustomDomains field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetCustomDomains() []CustomDomainStatus {
	if o == nil || IsNil(o.CustomDomains) {
		var ret []CustomDomainStatus
		return ret
	}
	return o.CustomDomains
}

// GetCustomDomainsOk returns a tuple with the CustomDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetCustomDomainsOk() ([]CustomDomainStatus, bool) {
	if o == nil || IsNil(o.CustomDomains) {
		return nil, false
	}
	return o.CustomDomains, true
}

// HasCustomDomains returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasCustomDomains() bool {
	if o != nil && !IsNil(o.CustomDomains) {
		return true
	}

	return false
}

// SetCustomDomains gets a reference to the given []CustomDomainStatus and assigns it to the CustomDomains field.
func (o *ResourceStatusDetail) SetCustomDomains(v []CustomDomainStatus) {
	o.CustomDomains = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLinks() []LinkStatus {
	if o == nil || IsNil(o.Links) {
		var ret []LinkStatus
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLinksOk() ([]LinkStatus, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []LinkStatus and assigns it to the Links field.
func (o *ResourceStatusDetail) SetLinks(v []LinkStatus) {
	o.Links = v
}

// GetPrimaryDeploymentId returns the PrimaryDeploymentId field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetPrimaryDeploymentId() string {
	if o == nil || IsNil(o.PrimaryDeploymentId) {
		var ret string
		return ret
	}
	return *o.PrimaryDeploymentId
}

// GetPrimaryDeploymentIdOk returns a tuple with the PrimaryDeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetPrimaryDeploymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryDeploymentId) {
		return nil, false
	}
	return o.PrimaryDeploymentId, true
}

// HasPrimaryDeploymentId returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasPrimaryDeploymentId() bool {
	if o != nil && !IsNil(o.PrimaryDeploymentId) {
		return true
	}

	return false
}

// SetPrimaryDeploymentId gets a reference to the given string and assigns it to the PrimaryDeploymentId field.
func (o *ResourceStatusDetail) SetPrimaryDeploymentId(v string) {
	o.PrimaryDeploymentId = &v
}

// GetPrimaryImage returns the PrimaryImage field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetPrimaryImage() string {
	if o == nil || IsNil(o.PrimaryImage) {
		var ret string
		return ret
	}
	return *o.PrimaryImage
}

// GetPrimaryImageOk returns a tuple with the PrimaryImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetPrimaryImageOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryImage) {
		return nil, false
	}
	return o.PrimaryImage, true
}

// HasPrimaryImage returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasPrimaryImage() bool {
	if o != nil && !IsNil(o.PrimaryImage) {
		return true
	}

	return false
}

// SetPrimaryImage gets a reference to the given string and assigns it to the PrimaryImage field.
func (o *ResourceStatusDetail) SetPrimaryImage(v string) {
	o.PrimaryImage = &v
}

// GetLastDeploymentTime returns the LastDeploymentTime field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLastDeploymentTime() time.Time {
	if o == nil || IsNil(o.LastDeploymentTime) {
		var ret time.Time
		return ret
	}
	return *o.LastDeploymentTime
}

// GetLastDeploymentTimeOk returns a tuple with the LastDeploymentTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLastDeploymentTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastDeploymentTime) {
		return nil, false
	}
	return o.LastDeploymentTime, true
}

// HasLastDeploymentTime returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLastDeploymentTime() bool {
	if o != nil && !IsNil(o.LastDeploymentTime) {
		return true
	}

	return false
}

// SetLastDeploymentTime gets a reference to the given time.Time and assigns it to the LastDeploymentTime field.
func (o *ResourceStatusDetail) SetLastDeploymentTime(v time.Time) {
	o.LastDeploymentTime = &v
}

// GetLastSyncTime returns the LastSyncTime field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLastSyncTime() time.Time {
	if o == nil || IsNil(o.LastSyncTime) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncTime
}

// GetLastSyncTimeOk returns a tuple with the LastSyncTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLastSyncTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSyncTime) {
		return nil, false
	}
	return o.LastSyncTime, true
}

// HasLastSyncTime returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLastSyncTime() bool {
	if o != nil && !IsNil(o.LastSyncTime) {
		return true
	}

	return false
}

// SetLastSyncTime gets a reference to the given time.Time and assigns it to the LastSyncTime field.
func (o *ResourceStatusDetail) SetLastSyncTime(v time.Time) {
	o.LastSyncTime = &v
}

// GetLatestDeploymentId returns the LatestDeploymentId field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLatestDeploymentId() string {
	if o == nil || IsNil(o.LatestDeploymentId) {
		var ret string
		return ret
	}
	return *o.LatestDeploymentId
}

// GetLatestDeploymentIdOk returns a tuple with the LatestDeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLatestDeploymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.LatestDeploymentId) {
		return nil, false
	}
	return o.LatestDeploymentId, true
}

// HasLatestDeploymentId returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLatestDeploymentId() bool {
	if o != nil && !IsNil(o.LatestDeploymentId) {
		return true
	}

	return false
}

// SetLatestDeploymentId gets a reference to the given string and assigns it to the LatestDeploymentId field.
func (o *ResourceStatusDetail) SetLatestDeploymentId(v string) {
	o.LatestDeploymentId = &v
}

// GetLatestDeploymentStatus returns the LatestDeploymentStatus field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLatestDeploymentStatus() string {
	if o == nil || IsNil(o.LatestDeploymentStatus) {
		var ret string
		return ret
	}
	return *o.LatestDeploymentStatus
}

// GetLatestDeploymentStatusOk returns a tuple with the LatestDeploymentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLatestDeploymentStatusOk() (*string, bool) {
	if o == nil || IsNil(o.LatestDeploymentStatus) {
		return nil, false
	}
	return o.LatestDeploymentStatus, true
}

// HasLatestDeploymentStatus returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLatestDeploymentStatus() bool {
	if o != nil && !IsNil(o.LatestDeploymentStatus) {
		return true
	}

	return false
}

// SetLatestDeploymentStatus gets a reference to the given string and assigns it to the LatestDeploymentStatus field.
func (o *ResourceStatusDetail) SetLatestDeploymentStatus(v string) {
	o.LatestDeploymentStatus = &v
}

func (o ResourceStatusDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceStatusDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ObservedGeneration) {
		toSerialize["observedGeneration"] = o.ObservedGeneration
	}
	if !IsNil(o.Replicas) {
		toSerialize["replicas"] = o.Replicas
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.CustomDomains) {
		toSerialize["customDomains"] = o.CustomDomains
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.PrimaryDeploymentId) {
		toSerialize["primaryDeploymentId"] = o.PrimaryDeploymentId
	}
	if !IsNil(o.PrimaryImage) {
		toSerialize["primaryImage"] = o.PrimaryImage
	}
	if !IsNil(o.LastDeploymentTime) {
		toSerialize["lastDeploymentTime"] = o.LastDeploymentTime
	}
	if !IsNil(o.LastSyncTime) {
		toSerialize["lastSyncTime"] = o.LastSyncTime
	}
	if !IsNil(o.LatestDeploymentId) {
		toSerialize["latestDeploymentId"] = o.LatestDeploymentId
	}
	if !IsNil(o.LatestDeploymentStatus) {
		toSerialize["latestDeploymentStatus"] = o.LatestDeploymentStatus
	}
	return toSerialize, nil
}

type NullableResourceStatusDetail struct {
	value *ResourceStatusDetail
	isSet bool
}

func (v NullableResourceStatusDetail) Get() *ResourceStatusDetail {
	return v.value
}

func (v *NullableResourceStatusDetail) Set(val *ResourceStatusDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceStatusDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceStatusDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceStatusDetail(val *ResourceStatusDetail) *NullableResourceStatusDetail {
	return &NullableResourceStatusDetail{value: val, isSet: true}
}

func (v NullableResourceStatusDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceStatusDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
