/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PlatformConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlatformConfig{}

// PlatformConfig struct for PlatformConfig
type PlatformConfig struct {
	Domain *string `json:"domain,omitempty"`
	Registry *RegistryConfig `json:"registry,omitempty"`
	Branding *PlatformConfigBranding `json:"branding,omitempty"`
	Auth map[string]interface{} `json:"auth,omitempty"`
	DefaultQuota *Quota `json:"defaultQuota,omitempty"`
	BuildConfig map[string]interface{} `json:"buildConfig,omitempty"`
}

// NewPlatformConfig instantiates a new PlatformConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformConfig() *PlatformConfig {
	this := PlatformConfig{}
	return &this
}

// NewPlatformConfigWithDefaults instantiates a new PlatformConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformConfigWithDefaults() *PlatformConfig {
	this := PlatformConfig{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *PlatformConfig) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformConfig) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *PlatformConfig) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *PlatformConfig) SetDomain(v string) {
	o.Domain = &v
}

// GetRegistry returns the Registry field value if set, zero value otherwise.
func (o *PlatformConfig) GetRegistry() RegistryConfig {
	if o == nil || IsNil(o.Registry) {
		var ret RegistryConfig
		return ret
	}
	return *o.Registry
}

// GetRegistryOk returns a tuple with the Registry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformConfig) GetRegistryOk() (*RegistryConfig, bool) {
	if o == nil || IsNil(o.Registry) {
		return nil, false
	}
	return o.Registry, true
}

// HasRegistry returns a boolean if a field has been set.
func (o *PlatformConfig) HasRegistry() bool {
	if o != nil && !IsNil(o.Registry) {
		return true
	}

	return false
}

// SetRegistry gets a reference to the given RegistryConfig and assigns it to the Registry field.
func (o *PlatformConfig) SetRegistry(v RegistryConfig) {
	o.Registry = &v
}

// GetBranding returns the Branding field value if set, zero value otherwise.
func (o *PlatformConfig) GetBranding() PlatformConfigBranding {
	if o == nil || IsNil(o.Branding) {
		var ret PlatformConfigBranding
		return ret
	}
	return *o.Branding
}

// GetBrandingOk returns a tuple with the Branding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformConfig) GetBrandingOk() (*PlatformConfigBranding, bool) {
	if o == nil || IsNil(o.Branding) {
		return nil, false
	}
	return o.Branding, true
}

// HasBranding returns a boolean if a field has been set.
func (o *PlatformConfig) HasBranding() bool {
	if o != nil && !IsNil(o.Branding) {
		return true
	}

	return false
}

// SetBranding gets a reference to the given PlatformConfigBranding and assigns it to the Branding field.
func (o *PlatformConfig) SetBranding(v PlatformConfigBranding) {
	o.Branding = &v
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *PlatformConfig) GetAuth() map[string]interface{} {
	if o == nil || IsNil(o.Auth) {
		var ret map[string]interface{}
		return ret
	}
	return o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformConfig) GetAuthOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Auth) {
		return map[string]interface{}{}, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *PlatformConfig) HasAuth() bool {
	if o != nil && !IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given map[string]interface{} and assigns it to the Auth field.
func (o *PlatformConfig) SetAuth(v map[string]interface{}) {
	o.Auth = v
}

// GetDefaultQuota returns the DefaultQuota field value if set, zero value otherwise.
func (o *PlatformConfig) GetDefaultQuota() Quota {
	if o == nil || IsNil(o.DefaultQuota) {
		var ret Quota
		return ret
	}
	return *o.DefaultQuota
}

// GetDefaultQuotaOk returns a tuple with the DefaultQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformConfig) GetDefaultQuotaOk() (*Quota, bool) {
	if o == nil || IsNil(o.DefaultQuota) {
		return nil, false
	}
	return o.DefaultQuota, true
}

// HasDefaultQuota returns a boolean if a field has been set.
func (o *PlatformConfig) HasDefaultQuota() bool {
	if o != nil && !IsNil(o.DefaultQuota) {
		return true
	}

	return false
}

// SetDefaultQuota gets a reference to the given Quota and assigns it to the DefaultQuota field.
func (o *PlatformConfig) SetDefaultQuota(v Quota) {
	o.DefaultQuota = &v
}

// GetBuildConfig returns the BuildConfig field value if set, zero value otherwise.
func (o *PlatformConfig) GetBuildConfig() map[string]interface{} {
	if o == nil || IsNil(o.BuildConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.BuildConfig
}

// GetBuildConfigOk returns a tuple with the BuildConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformConfig) GetBuildConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.BuildConfig) {
		return map[string]interface{}{}, false
	}
	return o.BuildConfig, true
}

// HasBuildConfig returns a boolean if a field has been set.
func (o *PlatformConfig) HasBuildConfig() bool {
	if o != nil && !IsNil(o.BuildConfig) {
		return true
	}

	return false
}

// SetBuildConfig gets a reference to the given map[string]interface{} and assigns it to the BuildConfig field.
func (o *PlatformConfig) SetBuildConfig(v map[string]interface{}) {
	o.BuildConfig = v
}

func (o PlatformConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlatformConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Registry) {
		toSerialize["registry"] = o.Registry
	}
	if !IsNil(o.Branding) {
		toSerialize["branding"] = o.Branding
	}
	if !IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	if !IsNil(o.DefaultQuota) {
		toSerialize["defaultQuota"] = o.DefaultQuota
	}
	if !IsNil(o.BuildConfig) {
		toSerialize["buildConfig"] = o.BuildConfig
	}
	return toSerialize, nil
}

type NullablePlatformConfig struct {
	value *PlatformConfig
	isSet bool
}

func (v NullablePlatformConfig) Get() *PlatformConfig {
	return v.value
}

func (v *NullablePlatformConfig) Set(val *PlatformConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformConfig(val *PlatformConfig) *NullablePlatformConfig {
	return &NullablePlatformConfig{value: val, isSet: true}
}

func (v NullablePlatformConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


