/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the ResourceStatusDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceStatusDetail{}

// ResourceStatusDetail struct for ResourceStatusDetail
type ResourceStatusDetail struct {
	Phase                     *string              `json:"phase,omitempty"`
	Message                   *string              `json:"message,omitempty"`
	ObservedGeneration        *int64               `json:"observedGeneration,omitempty"`
	Replicas                  *ReplicaStatus       `json:"replicas,omitempty"`
	Conditions                []ResourceCondition  `json:"conditions,omitempty"`
	CustomDomains             []CustomDomainStatus `json:"customDomains,omitempty"`
	Links                     []LinkStatus         `json:"links,omitempty"`
	LastSyncTime              *time.Time           `json:"lastSyncTime,omitempty"`
	ActiveRelease             *ActiveRelease       `json:"activeRelease,omitempty"`
	ObservedReleaseId         *string              `json:"observedReleaseId,omitempty"`
	ObservedRestartGeneration *int64               `json:"observedRestartGeneration,omitempty"`
	ObservedEnvHash           *string              `json:"observedEnvHash,omitempty"`
	ObservedPinnedImageRef    *string              `json:"observedPinnedImageRef,omitempty"`
	RolloutStatus             *string              `json:"rolloutStatus,omitempty"`
	ReplicasReady             *int32               `json:"replicasReady,omitempty"`
	SyncFailed                *bool                `json:"syncFailed,omitempty"`
	LastError                 *string              `json:"lastError,omitempty"`
	ProbeStatus               *ProbeStatusBlock    `json:"probeStatus,omitempty"`
}

// NewResourceStatusDetail instantiates a new ResourceStatusDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceStatusDetail() *ResourceStatusDetail {
	this := ResourceStatusDetail{}
	return &this
}

// NewResourceStatusDetailWithDefaults instantiates a new ResourceStatusDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceStatusDetailWithDefaults() *ResourceStatusDetail {
	this := ResourceStatusDetail{}
	return &this
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *ResourceStatusDetail) SetPhase(v string) {
	o.Phase = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResourceStatusDetail) SetMessage(v string) {
	o.Message = &v
}

// GetObservedGeneration returns the ObservedGeneration field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetObservedGeneration() int64 {
	if o == nil || IsNil(o.ObservedGeneration) {
		var ret int64
		return ret
	}
	return *o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetObservedGenerationOk() (*int64, bool) {
	if o == nil || IsNil(o.ObservedGeneration) {
		return nil, false
	}
	return o.ObservedGeneration, true
}

// HasObservedGeneration returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasObservedGeneration() bool {
	if o != nil && !IsNil(o.ObservedGeneration) {
		return true
	}

	return false
}

// SetObservedGeneration gets a reference to the given int64 and assigns it to the ObservedGeneration field.
func (o *ResourceStatusDetail) SetObservedGeneration(v int64) {
	o.ObservedGeneration = &v
}

// GetReplicas returns the Replicas field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetReplicas() ReplicaStatus {
	if o == nil || IsNil(o.Replicas) {
		var ret ReplicaStatus
		return ret
	}
	return *o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetReplicasOk() (*ReplicaStatus, bool) {
	if o == nil || IsNil(o.Replicas) {
		return nil, false
	}
	return o.Replicas, true
}

// HasReplicas returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasReplicas() bool {
	if o != nil && !IsNil(o.Replicas) {
		return true
	}

	return false
}

// SetReplicas gets a reference to the given ReplicaStatus and assigns it to the Replicas field.
func (o *ResourceStatusDetail) SetReplicas(v ReplicaStatus) {
	o.Replicas = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetConditions() []ResourceCondition {
	if o == nil || IsNil(o.Conditions) {
		var ret []ResourceCondition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetConditionsOk() ([]ResourceCondition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ResourceCondition and assigns it to the Conditions field.
func (o *ResourceStatusDetail) SetConditions(v []ResourceCondition) {
	o.Conditions = v
}

// GetCustomDomains returns the CustomDomains field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetCustomDomains() []CustomDomainStatus {
	if o == nil || IsNil(o.CustomDomains) {
		var ret []CustomDomainStatus
		return ret
	}
	return o.CustomDomains
}

// GetCustomDomainsOk returns a tuple with the CustomDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetCustomDomainsOk() ([]CustomDomainStatus, bool) {
	if o == nil || IsNil(o.CustomDomains) {
		return nil, false
	}
	return o.CustomDomains, true
}

// HasCustomDomains returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasCustomDomains() bool {
	if o != nil && !IsNil(o.CustomDomains) {
		return true
	}

	return false
}

// SetCustomDomains gets a reference to the given []CustomDomainStatus and assigns it to the CustomDomains field.
func (o *ResourceStatusDetail) SetCustomDomains(v []CustomDomainStatus) {
	o.CustomDomains = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLinks() []LinkStatus {
	if o == nil || IsNil(o.Links) {
		var ret []LinkStatus
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLinksOk() ([]LinkStatus, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []LinkStatus and assigns it to the Links field.
func (o *ResourceStatusDetail) SetLinks(v []LinkStatus) {
	o.Links = v
}

// GetLastSyncTime returns the LastSyncTime field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLastSyncTime() time.Time {
	if o == nil || IsNil(o.LastSyncTime) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncTime
}

// GetLastSyncTimeOk returns a tuple with the LastSyncTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLastSyncTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSyncTime) {
		return nil, false
	}
	return o.LastSyncTime, true
}

// HasLastSyncTime returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLastSyncTime() bool {
	if o != nil && !IsNil(o.LastSyncTime) {
		return true
	}

	return false
}

// SetLastSyncTime gets a reference to the given time.Time and assigns it to the LastSyncTime field.
func (o *ResourceStatusDetail) SetLastSyncTime(v time.Time) {
	o.LastSyncTime = &v
}

// GetActiveRelease returns the ActiveRelease field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetActiveRelease() ActiveRelease {
	if o == nil || IsNil(o.ActiveRelease) {
		var ret ActiveRelease
		return ret
	}
	return *o.ActiveRelease
}

// GetActiveReleaseOk returns a tuple with the ActiveRelease field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetActiveReleaseOk() (*ActiveRelease, bool) {
	if o == nil || IsNil(o.ActiveRelease) {
		return nil, false
	}
	return o.ActiveRelease, true
}

// HasActiveRelease returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasActiveRelease() bool {
	if o != nil && !IsNil(o.ActiveRelease) {
		return true
	}

	return false
}

// SetActiveRelease gets a reference to the given ActiveRelease and assigns it to the ActiveRelease field.
func (o *ResourceStatusDetail) SetActiveRelease(v ActiveRelease) {
	o.ActiveRelease = &v
}

// GetObservedReleaseId returns the ObservedReleaseId field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetObservedReleaseId() string {
	if o == nil || IsNil(o.ObservedReleaseId) {
		var ret string
		return ret
	}
	return *o.ObservedReleaseId
}

// GetObservedReleaseIdOk returns a tuple with the ObservedReleaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetObservedReleaseIdOk() (*string, bool) {
	if o == nil || IsNil(o.ObservedReleaseId) {
		return nil, false
	}
	return o.ObservedReleaseId, true
}

// HasObservedReleaseId returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasObservedReleaseId() bool {
	if o != nil && !IsNil(o.ObservedReleaseId) {
		return true
	}

	return false
}

// SetObservedReleaseId gets a reference to the given string and assigns it to the ObservedReleaseId field.
func (o *ResourceStatusDetail) SetObservedReleaseId(v string) {
	o.ObservedReleaseId = &v
}

// GetObservedRestartGeneration returns the ObservedRestartGeneration field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetObservedRestartGeneration() int64 {
	if o == nil || IsNil(o.ObservedRestartGeneration) {
		var ret int64
		return ret
	}
	return *o.ObservedRestartGeneration
}

// GetObservedRestartGenerationOk returns a tuple with the ObservedRestartGeneration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetObservedRestartGenerationOk() (*int64, bool) {
	if o == nil || IsNil(o.ObservedRestartGeneration) {
		return nil, false
	}
	return o.ObservedRestartGeneration, true
}

// HasObservedRestartGeneration returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasObservedRestartGeneration() bool {
	if o != nil && !IsNil(o.ObservedRestartGeneration) {
		return true
	}

	return false
}

// SetObservedRestartGeneration gets a reference to the given int64 and assigns it to the ObservedRestartGeneration field.
func (o *ResourceStatusDetail) SetObservedRestartGeneration(v int64) {
	o.ObservedRestartGeneration = &v
}

// GetObservedEnvHash returns the ObservedEnvHash field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetObservedEnvHash() string {
	if o == nil || IsNil(o.ObservedEnvHash) {
		var ret string
		return ret
	}
	return *o.ObservedEnvHash
}

// GetObservedEnvHashOk returns a tuple with the ObservedEnvHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetObservedEnvHashOk() (*string, bool) {
	if o == nil || IsNil(o.ObservedEnvHash) {
		return nil, false
	}
	return o.ObservedEnvHash, true
}

// HasObservedEnvHash returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasObservedEnvHash() bool {
	if o != nil && !IsNil(o.ObservedEnvHash) {
		return true
	}

	return false
}

// SetObservedEnvHash gets a reference to the given string and assigns it to the ObservedEnvHash field.
func (o *ResourceStatusDetail) SetObservedEnvHash(v string) {
	o.ObservedEnvHash = &v
}

// GetObservedPinnedImageRef returns the ObservedPinnedImageRef field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetObservedPinnedImageRef() string {
	if o == nil || IsNil(o.ObservedPinnedImageRef) {
		var ret string
		return ret
	}
	return *o.ObservedPinnedImageRef
}

// GetObservedPinnedImageRefOk returns a tuple with the ObservedPinnedImageRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetObservedPinnedImageRefOk() (*string, bool) {
	if o == nil || IsNil(o.ObservedPinnedImageRef) {
		return nil, false
	}
	return o.ObservedPinnedImageRef, true
}

// HasObservedPinnedImageRef returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasObservedPinnedImageRef() bool {
	if o != nil && !IsNil(o.ObservedPinnedImageRef) {
		return true
	}

	return false
}

// SetObservedPinnedImageRef gets a reference to the given string and assigns it to the ObservedPinnedImageRef field.
func (o *ResourceStatusDetail) SetObservedPinnedImageRef(v string) {
	o.ObservedPinnedImageRef = &v
}

// GetRolloutStatus returns the RolloutStatus field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetRolloutStatus() string {
	if o == nil || IsNil(o.RolloutStatus) {
		var ret string
		return ret
	}
	return *o.RolloutStatus
}

// GetRolloutStatusOk returns a tuple with the RolloutStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetRolloutStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RolloutStatus) {
		return nil, false
	}
	return o.RolloutStatus, true
}

// HasRolloutStatus returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasRolloutStatus() bool {
	if o != nil && !IsNil(o.RolloutStatus) {
		return true
	}

	return false
}

// SetRolloutStatus gets a reference to the given string and assigns it to the RolloutStatus field.
func (o *ResourceStatusDetail) SetRolloutStatus(v string) {
	o.RolloutStatus = &v
}

// GetReplicasReady returns the ReplicasReady field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetReplicasReady() int32 {
	if o == nil || IsNil(o.ReplicasReady) {
		var ret int32
		return ret
	}
	return *o.ReplicasReady
}

// GetReplicasReadyOk returns a tuple with the ReplicasReady field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetReplicasReadyOk() (*int32, bool) {
	if o == nil || IsNil(o.ReplicasReady) {
		return nil, false
	}
	return o.ReplicasReady, true
}

// HasReplicasReady returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasReplicasReady() bool {
	if o != nil && !IsNil(o.ReplicasReady) {
		return true
	}

	return false
}

// SetReplicasReady gets a reference to the given int32 and assigns it to the ReplicasReady field.
func (o *ResourceStatusDetail) SetReplicasReady(v int32) {
	o.ReplicasReady = &v
}

// GetSyncFailed returns the SyncFailed field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetSyncFailed() bool {
	if o == nil || IsNil(o.SyncFailed) {
		var ret bool
		return ret
	}
	return *o.SyncFailed
}

// GetSyncFailedOk returns a tuple with the SyncFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetSyncFailedOk() (*bool, bool) {
	if o == nil || IsNil(o.SyncFailed) {
		return nil, false
	}
	return o.SyncFailed, true
}

// HasSyncFailed returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasSyncFailed() bool {
	if o != nil && !IsNil(o.SyncFailed) {
		return true
	}

	return false
}

// SetSyncFailed gets a reference to the given bool and assigns it to the SyncFailed field.
func (o *ResourceStatusDetail) SetSyncFailed(v bool) {
	o.SyncFailed = &v
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetLastError() string {
	if o == nil || IsNil(o.LastError) {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetLastErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return o.LastError, true
}

// HasLastError returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasLastError() bool {
	if o != nil && !IsNil(o.LastError) {
		return true
	}

	return false
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *ResourceStatusDetail) SetLastError(v string) {
	o.LastError = &v
}

// GetProbeStatus returns the ProbeStatus field value if set, zero value otherwise.
func (o *ResourceStatusDetail) GetProbeStatus() ProbeStatusBlock {
	if o == nil || IsNil(o.ProbeStatus) {
		var ret ProbeStatusBlock
		return ret
	}
	return *o.ProbeStatus
}

// GetProbeStatusOk returns a tuple with the ProbeStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceStatusDetail) GetProbeStatusOk() (*ProbeStatusBlock, bool) {
	if o == nil || IsNil(o.ProbeStatus) {
		return nil, false
	}
	return o.ProbeStatus, true
}

// HasProbeStatus returns a boolean if a field has been set.
func (o *ResourceStatusDetail) HasProbeStatus() bool {
	if o != nil && !IsNil(o.ProbeStatus) {
		return true
	}

	return false
}

// SetProbeStatus gets a reference to the given ProbeStatusBlock and assigns it to the ProbeStatus field.
func (o *ResourceStatusDetail) SetProbeStatus(v ProbeStatusBlock) {
	o.ProbeStatus = &v
}

func (o ResourceStatusDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceStatusDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ObservedGeneration) {
		toSerialize["observedGeneration"] = o.ObservedGeneration
	}
	if !IsNil(o.Replicas) {
		toSerialize["replicas"] = o.Replicas
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.CustomDomains) {
		toSerialize["customDomains"] = o.CustomDomains
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.LastSyncTime) {
		toSerialize["lastSyncTime"] = o.LastSyncTime
	}
	if !IsNil(o.ActiveRelease) {
		toSerialize["activeRelease"] = o.ActiveRelease
	}
	if !IsNil(o.ObservedReleaseId) {
		toSerialize["observedReleaseId"] = o.ObservedReleaseId
	}
	if !IsNil(o.ObservedRestartGeneration) {
		toSerialize["observedRestartGeneration"] = o.ObservedRestartGeneration
	}
	if !IsNil(o.ObservedEnvHash) {
		toSerialize["observedEnvHash"] = o.ObservedEnvHash
	}
	if !IsNil(o.ObservedPinnedImageRef) {
		toSerialize["observedPinnedImageRef"] = o.ObservedPinnedImageRef
	}
	if !IsNil(o.RolloutStatus) {
		toSerialize["rolloutStatus"] = o.RolloutStatus
	}
	if !IsNil(o.ReplicasReady) {
		toSerialize["replicasReady"] = o.ReplicasReady
	}
	if !IsNil(o.SyncFailed) {
		toSerialize["syncFailed"] = o.SyncFailed
	}
	if !IsNil(o.LastError) {
		toSerialize["lastError"] = o.LastError
	}
	if !IsNil(o.ProbeStatus) {
		toSerialize["probeStatus"] = o.ProbeStatus
	}
	return toSerialize, nil
}

type NullableResourceStatusDetail struct {
	value *ResourceStatusDetail
	isSet bool
}

func (v NullableResourceStatusDetail) Get() *ResourceStatusDetail {
	return v.value
}

func (v *NullableResourceStatusDetail) Set(val *ResourceStatusDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceStatusDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceStatusDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceStatusDetail(val *ResourceStatusDetail) *NullableResourceStatusDetail {
	return &NullableResourceStatusDetail{value: val, isSet: true}
}

func (v NullableResourceStatusDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceStatusDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
