/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ResourcePreviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourcePreviewResponse{}

// ResourcePreviewResponse struct for ResourcePreviewResponse
type ResourcePreviewResponse struct {
	Slug   *string `json:"slug,omitempty"`
	Domain *string `json:"domain,omitempty"`
}

// NewResourcePreviewResponse instantiates a new ResourcePreviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourcePreviewResponse() *ResourcePreviewResponse {
	this := ResourcePreviewResponse{}
	return &this
}

// NewResourcePreviewResponseWithDefaults instantiates a new ResourcePreviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourcePreviewResponseWithDefaults() *ResourcePreviewResponse {
	this := ResourcePreviewResponse{}
	return &this
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ResourcePreviewResponse) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourcePreviewResponse) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ResourcePreviewResponse) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ResourcePreviewResponse) SetSlug(v string) {
	o.Slug = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *ResourcePreviewResponse) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourcePreviewResponse) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *ResourcePreviewResponse) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *ResourcePreviewResponse) SetDomain(v string) {
	o.Domain = &v
}

func (o ResourcePreviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourcePreviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	return toSerialize, nil
}

type NullableResourcePreviewResponse struct {
	value *ResourcePreviewResponse
	isSet bool
}

func (v NullableResourcePreviewResponse) Get() *ResourcePreviewResponse {
	return v.value
}

func (v *NullableResourcePreviewResponse) Set(val *ResourcePreviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResourcePreviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResourcePreviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourcePreviewResponse(val *ResourcePreviewResponse) *NullableResourcePreviewResponse {
	return &NullableResourcePreviewResponse{value: val, isSet: true}
}

func (v NullableResourcePreviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourcePreviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
