/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNetworkPolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNetworkPolicyRequest{}

// CreateNetworkPolicyRequest struct for CreateNetworkPolicyRequest
type CreateNetworkPolicyRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	WorkspaceId *string `json:"workspaceId,omitempty"`
	Policy map[string]interface{} `json:"policy"`
}

type _CreateNetworkPolicyRequest CreateNetworkPolicyRequest

// NewCreateNetworkPolicyRequest instantiates a new CreateNetworkPolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNetworkPolicyRequest(name string, policy map[string]interface{}) *CreateNetworkPolicyRequest {
	this := CreateNetworkPolicyRequest{}
	this.Name = name
	this.Policy = policy
	return &this
}

// NewCreateNetworkPolicyRequestWithDefaults instantiates a new CreateNetworkPolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNetworkPolicyRequestWithDefaults() *CreateNetworkPolicyRequest {
	this := CreateNetworkPolicyRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateNetworkPolicyRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateNetworkPolicyRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateNetworkPolicyRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateNetworkPolicyRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkPolicyRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateNetworkPolicyRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateNetworkPolicyRequest) SetDescription(v string) {
	o.Description = &v
}

// GetWorkspaceId returns the WorkspaceId field value if set, zero value otherwise.
func (o *CreateNetworkPolicyRequest) GetWorkspaceId() string {
	if o == nil || IsNil(o.WorkspaceId) {
		var ret string
		return ret
	}
	return *o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkPolicyRequest) GetWorkspaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkspaceId) {
		return nil, false
	}
	return o.WorkspaceId, true
}

// HasWorkspaceId returns a boolean if a field has been set.
func (o *CreateNetworkPolicyRequest) HasWorkspaceId() bool {
	if o != nil && !IsNil(o.WorkspaceId) {
		return true
	}

	return false
}

// SetWorkspaceId gets a reference to the given string and assigns it to the WorkspaceId field.
func (o *CreateNetworkPolicyRequest) SetWorkspaceId(v string) {
	o.WorkspaceId = &v
}

// GetPolicy returns the Policy field value
func (o *CreateNetworkPolicyRequest) GetPolicy() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *CreateNetworkPolicyRequest) GetPolicyOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Policy, true
}

// SetPolicy sets field value
func (o *CreateNetworkPolicyRequest) SetPolicy(v map[string]interface{}) {
	o.Policy = v
}

func (o CreateNetworkPolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNetworkPolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.WorkspaceId) {
		toSerialize["workspaceId"] = o.WorkspaceId
	}
	toSerialize["policy"] = o.Policy
	return toSerialize, nil
}

func (o *CreateNetworkPolicyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNetworkPolicyRequest := _CreateNetworkPolicyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNetworkPolicyRequest)

	if err != nil {
		return err
	}

	*o = CreateNetworkPolicyRequest(varCreateNetworkPolicyRequest)

	return err
}

type NullableCreateNetworkPolicyRequest struct {
	value *CreateNetworkPolicyRequest
	isSet bool
}

func (v NullableCreateNetworkPolicyRequest) Get() *CreateNetworkPolicyRequest {
	return v.value
}

func (v *NullableCreateNetworkPolicyRequest) Set(val *CreateNetworkPolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNetworkPolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNetworkPolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNetworkPolicyRequest(val *CreateNetworkPolicyRequest) *NullableCreateNetworkPolicyRequest {
	return &NullableCreateNetworkPolicyRequest{value: val, isSet: true}
}

func (v NullableCreateNetworkPolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNetworkPolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


