/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the Quota type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Quota{}

// Quota struct for Quota
type Quota struct {
	MaxCpuCores *float64 `json:"maxCpuCores,omitempty"`
	MaxMemoryMb *int32 `json:"maxMemoryMb,omitempty"`
	MaxStorageGb *int32 `json:"maxStorageGb,omitempty"`
	MaxResources *int32 `json:"maxResources,omitempty"`
	MaxDeploymentResources *int32 `json:"maxDeploymentResources,omitempty"`
	MaxDatabaseResources *int32 `json:"maxDatabaseResources,omitempty"`
}

// NewQuota instantiates a new Quota object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuota() *Quota {
	this := Quota{}
	return &this
}

// NewQuotaWithDefaults instantiates a new Quota object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaWithDefaults() *Quota {
	this := Quota{}
	return &this
}

// GetMaxCpuCores returns the MaxCpuCores field value if set, zero value otherwise.
func (o *Quota) GetMaxCpuCores() float64 {
	if o == nil || IsNil(o.MaxCpuCores) {
		var ret float64
		return ret
	}
	return *o.MaxCpuCores
}

// GetMaxCpuCoresOk returns a tuple with the MaxCpuCores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quota) GetMaxCpuCoresOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxCpuCores) {
		return nil, false
	}
	return o.MaxCpuCores, true
}

// HasMaxCpuCores returns a boolean if a field has been set.
func (o *Quota) HasMaxCpuCores() bool {
	if o != nil && !IsNil(o.MaxCpuCores) {
		return true
	}

	return false
}

// SetMaxCpuCores gets a reference to the given float64 and assigns it to the MaxCpuCores field.
func (o *Quota) SetMaxCpuCores(v float64) {
	o.MaxCpuCores = &v
}

// GetMaxMemoryMb returns the MaxMemoryMb field value if set, zero value otherwise.
func (o *Quota) GetMaxMemoryMb() int32 {
	if o == nil || IsNil(o.MaxMemoryMb) {
		var ret int32
		return ret
	}
	return *o.MaxMemoryMb
}

// GetMaxMemoryMbOk returns a tuple with the MaxMemoryMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quota) GetMaxMemoryMbOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxMemoryMb) {
		return nil, false
	}
	return o.MaxMemoryMb, true
}

// HasMaxMemoryMb returns a boolean if a field has been set.
func (o *Quota) HasMaxMemoryMb() bool {
	if o != nil && !IsNil(o.MaxMemoryMb) {
		return true
	}

	return false
}

// SetMaxMemoryMb gets a reference to the given int32 and assigns it to the MaxMemoryMb field.
func (o *Quota) SetMaxMemoryMb(v int32) {
	o.MaxMemoryMb = &v
}

// GetMaxStorageGb returns the MaxStorageGb field value if set, zero value otherwise.
func (o *Quota) GetMaxStorageGb() int32 {
	if o == nil || IsNil(o.MaxStorageGb) {
		var ret int32
		return ret
	}
	return *o.MaxStorageGb
}

// GetMaxStorageGbOk returns a tuple with the MaxStorageGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quota) GetMaxStorageGbOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxStorageGb) {
		return nil, false
	}
	return o.MaxStorageGb, true
}

// HasMaxStorageGb returns a boolean if a field has been set.
func (o *Quota) HasMaxStorageGb() bool {
	if o != nil && !IsNil(o.MaxStorageGb) {
		return true
	}

	return false
}

// SetMaxStorageGb gets a reference to the given int32 and assigns it to the MaxStorageGb field.
func (o *Quota) SetMaxStorageGb(v int32) {
	o.MaxStorageGb = &v
}

// GetMaxResources returns the MaxResources field value if set, zero value otherwise.
func (o *Quota) GetMaxResources() int32 {
	if o == nil || IsNil(o.MaxResources) {
		var ret int32
		return ret
	}
	return *o.MaxResources
}

// GetMaxResourcesOk returns a tuple with the MaxResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quota) GetMaxResourcesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxResources) {
		return nil, false
	}
	return o.MaxResources, true
}

// HasMaxResources returns a boolean if a field has been set.
func (o *Quota) HasMaxResources() bool {
	if o != nil && !IsNil(o.MaxResources) {
		return true
	}

	return false
}

// SetMaxResources gets a reference to the given int32 and assigns it to the MaxResources field.
func (o *Quota) SetMaxResources(v int32) {
	o.MaxResources = &v
}

// GetMaxDeploymentResources returns the MaxDeploymentResources field value if set, zero value otherwise.
func (o *Quota) GetMaxDeploymentResources() int32 {
	if o == nil || IsNil(o.MaxDeploymentResources) {
		var ret int32
		return ret
	}
	return *o.MaxDeploymentResources
}

// GetMaxDeploymentResourcesOk returns a tuple with the MaxDeploymentResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quota) GetMaxDeploymentResourcesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDeploymentResources) {
		return nil, false
	}
	return o.MaxDeploymentResources, true
}

// HasMaxDeploymentResources returns a boolean if a field has been set.
func (o *Quota) HasMaxDeploymentResources() bool {
	if o != nil && !IsNil(o.MaxDeploymentResources) {
		return true
	}

	return false
}

// SetMaxDeploymentResources gets a reference to the given int32 and assigns it to the MaxDeploymentResources field.
func (o *Quota) SetMaxDeploymentResources(v int32) {
	o.MaxDeploymentResources = &v
}

// GetMaxDatabaseResources returns the MaxDatabaseResources field value if set, zero value otherwise.
func (o *Quota) GetMaxDatabaseResources() int32 {
	if o == nil || IsNil(o.MaxDatabaseResources) {
		var ret int32
		return ret
	}
	return *o.MaxDatabaseResources
}

// GetMaxDatabaseResourcesOk returns a tuple with the MaxDatabaseResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quota) GetMaxDatabaseResourcesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDatabaseResources) {
		return nil, false
	}
	return o.MaxDatabaseResources, true
}

// HasMaxDatabaseResources returns a boolean if a field has been set.
func (o *Quota) HasMaxDatabaseResources() bool {
	if o != nil && !IsNil(o.MaxDatabaseResources) {
		return true
	}

	return false
}

// SetMaxDatabaseResources gets a reference to the given int32 and assigns it to the MaxDatabaseResources field.
func (o *Quota) SetMaxDatabaseResources(v int32) {
	o.MaxDatabaseResources = &v
}

func (o Quota) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Quota) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxCpuCores) {
		toSerialize["maxCpuCores"] = o.MaxCpuCores
	}
	if !IsNil(o.MaxMemoryMb) {
		toSerialize["maxMemoryMb"] = o.MaxMemoryMb
	}
	if !IsNil(o.MaxStorageGb) {
		toSerialize["maxStorageGb"] = o.MaxStorageGb
	}
	if !IsNil(o.MaxResources) {
		toSerialize["maxResources"] = o.MaxResources
	}
	if !IsNil(o.MaxDeploymentResources) {
		toSerialize["maxDeploymentResources"] = o.MaxDeploymentResources
	}
	if !IsNil(o.MaxDatabaseResources) {
		toSerialize["maxDatabaseResources"] = o.MaxDatabaseResources
	}
	return toSerialize, nil
}

type NullableQuota struct {
	value *Quota
	isSet bool
}

func (v NullableQuota) Get() *Quota {
	return v.value
}

func (v *NullableQuota) Set(val *Quota) {
	v.value = val
	v.isSet = true
}

func (v NullableQuota) IsSet() bool {
	return v.isSet
}

func (v *NullableQuota) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuota(val *Quota) *NullableQuota {
	return &NullableQuota{value: val, isSet: true}
}

func (v NullableQuota) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuota) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


