/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the ProjectStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectStats{}

// ProjectStats struct for ProjectStats
type ProjectStats struct {
	Slug         *string             `json:"slug,omitempty"`
	Services     *int64              `json:"services,omitempty"`
	Deploys7d    *int64              `json:"deploys7d,omitempty"`
	UptimePct    *float64            `json:"uptimePct,omitempty"`
	LastDeployAt *time.Time          `json:"lastDeployAt,omitempty"`
	Envs         []EnvironmentRollup `json:"envs,omitempty"`
}

// NewProjectStats instantiates a new ProjectStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectStats() *ProjectStats {
	this := ProjectStats{}
	return &this
}

// NewProjectStatsWithDefaults instantiates a new ProjectStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectStatsWithDefaults() *ProjectStats {
	this := ProjectStats{}
	return &this
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ProjectStats) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStats) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ProjectStats) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ProjectStats) SetSlug(v string) {
	o.Slug = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ProjectStats) GetServices() int64 {
	if o == nil || IsNil(o.Services) {
		var ret int64
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStats) GetServicesOk() (*int64, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ProjectStats) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given int64 and assigns it to the Services field.
func (o *ProjectStats) SetServices(v int64) {
	o.Services = &v
}

// GetDeploys7d returns the Deploys7d field value if set, zero value otherwise.
func (o *ProjectStats) GetDeploys7d() int64 {
	if o == nil || IsNil(o.Deploys7d) {
		var ret int64
		return ret
	}
	return *o.Deploys7d
}

// GetDeploys7dOk returns a tuple with the Deploys7d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStats) GetDeploys7dOk() (*int64, bool) {
	if o == nil || IsNil(o.Deploys7d) {
		return nil, false
	}
	return o.Deploys7d, true
}

// HasDeploys7d returns a boolean if a field has been set.
func (o *ProjectStats) HasDeploys7d() bool {
	if o != nil && !IsNil(o.Deploys7d) {
		return true
	}

	return false
}

// SetDeploys7d gets a reference to the given int64 and assigns it to the Deploys7d field.
func (o *ProjectStats) SetDeploys7d(v int64) {
	o.Deploys7d = &v
}

// GetUptimePct returns the UptimePct field value if set, zero value otherwise.
func (o *ProjectStats) GetUptimePct() float64 {
	if o == nil || IsNil(o.UptimePct) {
		var ret float64
		return ret
	}
	return *o.UptimePct
}

// GetUptimePctOk returns a tuple with the UptimePct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStats) GetUptimePctOk() (*float64, bool) {
	if o == nil || IsNil(o.UptimePct) {
		return nil, false
	}
	return o.UptimePct, true
}

// HasUptimePct returns a boolean if a field has been set.
func (o *ProjectStats) HasUptimePct() bool {
	if o != nil && !IsNil(o.UptimePct) {
		return true
	}

	return false
}

// SetUptimePct gets a reference to the given float64 and assigns it to the UptimePct field.
func (o *ProjectStats) SetUptimePct(v float64) {
	o.UptimePct = &v
}

// GetLastDeployAt returns the LastDeployAt field value if set, zero value otherwise.
func (o *ProjectStats) GetLastDeployAt() time.Time {
	if o == nil || IsNil(o.LastDeployAt) {
		var ret time.Time
		return ret
	}
	return *o.LastDeployAt
}

// GetLastDeployAtOk returns a tuple with the LastDeployAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStats) GetLastDeployAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastDeployAt) {
		return nil, false
	}
	return o.LastDeployAt, true
}

// HasLastDeployAt returns a boolean if a field has been set.
func (o *ProjectStats) HasLastDeployAt() bool {
	if o != nil && !IsNil(o.LastDeployAt) {
		return true
	}

	return false
}

// SetLastDeployAt gets a reference to the given time.Time and assigns it to the LastDeployAt field.
func (o *ProjectStats) SetLastDeployAt(v time.Time) {
	o.LastDeployAt = &v
}

// GetEnvs returns the Envs field value if set, zero value otherwise.
func (o *ProjectStats) GetEnvs() []EnvironmentRollup {
	if o == nil || IsNil(o.Envs) {
		var ret []EnvironmentRollup
		return ret
	}
	return o.Envs
}

// GetEnvsOk returns a tuple with the Envs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStats) GetEnvsOk() ([]EnvironmentRollup, bool) {
	if o == nil || IsNil(o.Envs) {
		return nil, false
	}
	return o.Envs, true
}

// HasEnvs returns a boolean if a field has been set.
func (o *ProjectStats) HasEnvs() bool {
	if o != nil && !IsNil(o.Envs) {
		return true
	}

	return false
}

// SetEnvs gets a reference to the given []EnvironmentRollup and assigns it to the Envs field.
func (o *ProjectStats) SetEnvs(v []EnvironmentRollup) {
	o.Envs = v
}

func (o ProjectStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.Deploys7d) {
		toSerialize["deploys7d"] = o.Deploys7d
	}
	if !IsNil(o.UptimePct) {
		toSerialize["uptimePct"] = o.UptimePct
	}
	if !IsNil(o.LastDeployAt) {
		toSerialize["lastDeployAt"] = o.LastDeployAt
	}
	if !IsNil(o.Envs) {
		toSerialize["envs"] = o.Envs
	}
	return toSerialize, nil
}

type NullableProjectStats struct {
	value *ProjectStats
	isSet bool
}

func (v NullableProjectStats) Get() *ProjectStats {
	return v.value
}

func (v *NullableProjectStats) Set(val *ProjectStats) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectStats) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectStats(val *ProjectStats) *NullableProjectStats {
	return &NullableProjectStats{value: val, isSet: true}
}

func (v NullableProjectStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
