/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ClusterConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterConfig{}

// ClusterConfig struct for ClusterConfig
type ClusterConfig struct {
	NodePools []NodePool `json:"nodePools,omitempty"`
}

// NewClusterConfig instantiates a new ClusterConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterConfig() *ClusterConfig {
	this := ClusterConfig{}
	return &this
}

// NewClusterConfigWithDefaults instantiates a new ClusterConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterConfigWithDefaults() *ClusterConfig {
	this := ClusterConfig{}
	return &this
}

// GetNodePools returns the NodePools field value if set, zero value otherwise.
func (o *ClusterConfig) GetNodePools() []NodePool {
	if o == nil || IsNil(o.NodePools) {
		var ret []NodePool
		return ret
	}
	return o.NodePools
}

// GetNodePoolsOk returns a tuple with the NodePools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfig) GetNodePoolsOk() ([]NodePool, bool) {
	if o == nil || IsNil(o.NodePools) {
		return nil, false
	}
	return o.NodePools, true
}

// HasNodePools returns a boolean if a field has been set.
func (o *ClusterConfig) HasNodePools() bool {
	if o != nil && !IsNil(o.NodePools) {
		return true
	}

	return false
}

// SetNodePools gets a reference to the given []NodePool and assigns it to the NodePools field.
func (o *ClusterConfig) SetNodePools(v []NodePool) {
	o.NodePools = v
}

func (o ClusterConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NodePools) {
		toSerialize["nodePools"] = o.NodePools
	}
	return toSerialize, nil
}

type NullableClusterConfig struct {
	value *ClusterConfig
	isSet bool
}

func (v NullableClusterConfig) Get() *ClusterConfig {
	return v.value
}

func (v *NullableClusterConfig) Set(val *ClusterConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterConfig(val *ClusterConfig) *NullableClusterConfig {
	return &NullableClusterConfig{value: val, isSet: true}
}

func (v NullableClusterConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
