/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PeelboxBuildOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeelboxBuildOptions{}

// PeelboxBuildOptions struct for PeelboxBuildOptions
type PeelboxBuildOptions struct {
	Version  *string        `json:"version,omitempty"`
	Metadata *BuildMetadata `json:"metadata,omitempty"`
	Build    *BuildStage    `json:"build,omitempty"`
	Runtime  *RuntimeStage  `json:"runtime,omitempty"`
}

// NewPeelboxBuildOptions instantiates a new PeelboxBuildOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeelboxBuildOptions() *PeelboxBuildOptions {
	this := PeelboxBuildOptions{}
	return &this
}

// NewPeelboxBuildOptionsWithDefaults instantiates a new PeelboxBuildOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeelboxBuildOptionsWithDefaults() *PeelboxBuildOptions {
	this := PeelboxBuildOptions{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *PeelboxBuildOptions) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeelboxBuildOptions) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *PeelboxBuildOptions) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *PeelboxBuildOptions) SetVersion(v string) {
	o.Version = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PeelboxBuildOptions) GetMetadata() BuildMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret BuildMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeelboxBuildOptions) GetMetadataOk() (*BuildMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PeelboxBuildOptions) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given BuildMetadata and assigns it to the Metadata field.
func (o *PeelboxBuildOptions) SetMetadata(v BuildMetadata) {
	o.Metadata = &v
}

// GetBuild returns the Build field value if set, zero value otherwise.
func (o *PeelboxBuildOptions) GetBuild() BuildStage {
	if o == nil || IsNil(o.Build) {
		var ret BuildStage
		return ret
	}
	return *o.Build
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeelboxBuildOptions) GetBuildOk() (*BuildStage, bool) {
	if o == nil || IsNil(o.Build) {
		return nil, false
	}
	return o.Build, true
}

// HasBuild returns a boolean if a field has been set.
func (o *PeelboxBuildOptions) HasBuild() bool {
	if o != nil && !IsNil(o.Build) {
		return true
	}

	return false
}

// SetBuild gets a reference to the given BuildStage and assigns it to the Build field.
func (o *PeelboxBuildOptions) SetBuild(v BuildStage) {
	o.Build = &v
}

// GetRuntime returns the Runtime field value if set, zero value otherwise.
func (o *PeelboxBuildOptions) GetRuntime() RuntimeStage {
	if o == nil || IsNil(o.Runtime) {
		var ret RuntimeStage
		return ret
	}
	return *o.Runtime
}

// GetRuntimeOk returns a tuple with the Runtime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeelboxBuildOptions) GetRuntimeOk() (*RuntimeStage, bool) {
	if o == nil || IsNil(o.Runtime) {
		return nil, false
	}
	return o.Runtime, true
}

// HasRuntime returns a boolean if a field has been set.
func (o *PeelboxBuildOptions) HasRuntime() bool {
	if o != nil && !IsNil(o.Runtime) {
		return true
	}

	return false
}

// SetRuntime gets a reference to the given RuntimeStage and assigns it to the Runtime field.
func (o *PeelboxBuildOptions) SetRuntime(v RuntimeStage) {
	o.Runtime = &v
}

func (o PeelboxBuildOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeelboxBuildOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Build) {
		toSerialize["build"] = o.Build
	}
	if !IsNil(o.Runtime) {
		toSerialize["runtime"] = o.Runtime
	}
	return toSerialize, nil
}

type NullablePeelboxBuildOptions struct {
	value *PeelboxBuildOptions
	isSet bool
}

func (v NullablePeelboxBuildOptions) Get() *PeelboxBuildOptions {
	return v.value
}

func (v *NullablePeelboxBuildOptions) Set(val *PeelboxBuildOptions) {
	v.value = val
	v.isSet = true
}

func (v NullablePeelboxBuildOptions) IsSet() bool {
	return v.isSet
}

func (v *NullablePeelboxBuildOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeelboxBuildOptions(val *PeelboxBuildOptions) *NullablePeelboxBuildOptions {
	return &NullablePeelboxBuildOptions{value: val, isSet: true}
}

func (v NullablePeelboxBuildOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeelboxBuildOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
