/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BuildDetectionJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildDetectionJob{}

// BuildDetectionJob struct for BuildDetectionJob
type BuildDetectionJob struct {
	JobId          *string                  `json:"jobId,omitempty"`
	Status         *string                  `json:"status,omitempty"`
	Step           *string                  `json:"step,omitempty"`
	Message        *string                  `json:"message,omitempty"`
	UniversalBuild []map[string]interface{} `json:"universalBuild,omitempty"`
	Error          *string                  `json:"error,omitempty"`
}

// NewBuildDetectionJob instantiates a new BuildDetectionJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildDetectionJob() *BuildDetectionJob {
	this := BuildDetectionJob{}
	return &this
}

// NewBuildDetectionJobWithDefaults instantiates a new BuildDetectionJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildDetectionJobWithDefaults() *BuildDetectionJob {
	this := BuildDetectionJob{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *BuildDetectionJob) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetectionJob) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *BuildDetectionJob) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *BuildDetectionJob) SetJobId(v string) {
	o.JobId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BuildDetectionJob) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetectionJob) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BuildDetectionJob) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BuildDetectionJob) SetStatus(v string) {
	o.Status = &v
}

// GetStep returns the Step field value if set, zero value otherwise.
func (o *BuildDetectionJob) GetStep() string {
	if o == nil || IsNil(o.Step) {
		var ret string
		return ret
	}
	return *o.Step
}

// GetStepOk returns a tuple with the Step field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetectionJob) GetStepOk() (*string, bool) {
	if o == nil || IsNil(o.Step) {
		return nil, false
	}
	return o.Step, true
}

// HasStep returns a boolean if a field has been set.
func (o *BuildDetectionJob) HasStep() bool {
	if o != nil && !IsNil(o.Step) {
		return true
	}

	return false
}

// SetStep gets a reference to the given string and assigns it to the Step field.
func (o *BuildDetectionJob) SetStep(v string) {
	o.Step = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *BuildDetectionJob) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetectionJob) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *BuildDetectionJob) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *BuildDetectionJob) SetMessage(v string) {
	o.Message = &v
}

// GetUniversalBuild returns the UniversalBuild field value if set, zero value otherwise.
func (o *BuildDetectionJob) GetUniversalBuild() []map[string]interface{} {
	if o == nil || IsNil(o.UniversalBuild) {
		var ret []map[string]interface{}
		return ret
	}
	return o.UniversalBuild
}

// GetUniversalBuildOk returns a tuple with the UniversalBuild field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetectionJob) GetUniversalBuildOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.UniversalBuild) {
		return nil, false
	}
	return o.UniversalBuild, true
}

// HasUniversalBuild returns a boolean if a field has been set.
func (o *BuildDetectionJob) HasUniversalBuild() bool {
	if o != nil && !IsNil(o.UniversalBuild) {
		return true
	}

	return false
}

// SetUniversalBuild gets a reference to the given []map[string]interface{} and assigns it to the UniversalBuild field.
func (o *BuildDetectionJob) SetUniversalBuild(v []map[string]interface{}) {
	o.UniversalBuild = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *BuildDetectionJob) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetectionJob) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *BuildDetectionJob) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *BuildDetectionJob) SetError(v string) {
	o.Error = &v
}

func (o BuildDetectionJob) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildDetectionJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Step) {
		toSerialize["step"] = o.Step
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.UniversalBuild) {
		toSerialize["universalBuild"] = o.UniversalBuild
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableBuildDetectionJob struct {
	value *BuildDetectionJob
	isSet bool
}

func (v NullableBuildDetectionJob) Get() *BuildDetectionJob {
	return v.value
}

func (v *NullableBuildDetectionJob) Set(val *BuildDetectionJob) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildDetectionJob) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildDetectionJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildDetectionJob(val *BuildDetectionJob) *NullableBuildDetectionJob {
	return &NullableBuildDetectionJob{value: val, isSet: true}
}

func (v NullableBuildDetectionJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildDetectionJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
