/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ImageSourceGitSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageSourceGitSpec{}

// ImageSourceGitSpec struct for ImageSourceGitSpec
type ImageSourceGitSpec struct {
	Repo                 *string `json:"repo,omitempty"`
	Branch               *string `json:"branch,omitempty"`
	CredentialsSecretRef *string `json:"credentialsSecretRef,omitempty"`
}

// NewImageSourceGitSpec instantiates a new ImageSourceGitSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageSourceGitSpec() *ImageSourceGitSpec {
	this := ImageSourceGitSpec{}
	return &this
}

// NewImageSourceGitSpecWithDefaults instantiates a new ImageSourceGitSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageSourceGitSpecWithDefaults() *ImageSourceGitSpec {
	this := ImageSourceGitSpec{}
	return &this
}

// GetRepo returns the Repo field value if set, zero value otherwise.
func (o *ImageSourceGitSpec) GetRepo() string {
	if o == nil || IsNil(o.Repo) {
		var ret string
		return ret
	}
	return *o.Repo
}

// GetRepoOk returns a tuple with the Repo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourceGitSpec) GetRepoOk() (*string, bool) {
	if o == nil || IsNil(o.Repo) {
		return nil, false
	}
	return o.Repo, true
}

// HasRepo returns a boolean if a field has been set.
func (o *ImageSourceGitSpec) HasRepo() bool {
	if o != nil && !IsNil(o.Repo) {
		return true
	}

	return false
}

// SetRepo gets a reference to the given string and assigns it to the Repo field.
func (o *ImageSourceGitSpec) SetRepo(v string) {
	o.Repo = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *ImageSourceGitSpec) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourceGitSpec) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *ImageSourceGitSpec) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *ImageSourceGitSpec) SetBranch(v string) {
	o.Branch = &v
}

// GetCredentialsSecretRef returns the CredentialsSecretRef field value if set, zero value otherwise.
func (o *ImageSourceGitSpec) GetCredentialsSecretRef() string {
	if o == nil || IsNil(o.CredentialsSecretRef) {
		var ret string
		return ret
	}
	return *o.CredentialsSecretRef
}

// GetCredentialsSecretRefOk returns a tuple with the CredentialsSecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourceGitSpec) GetCredentialsSecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialsSecretRef) {
		return nil, false
	}
	return o.CredentialsSecretRef, true
}

// HasCredentialsSecretRef returns a boolean if a field has been set.
func (o *ImageSourceGitSpec) HasCredentialsSecretRef() bool {
	if o != nil && !IsNil(o.CredentialsSecretRef) {
		return true
	}

	return false
}

// SetCredentialsSecretRef gets a reference to the given string and assigns it to the CredentialsSecretRef field.
func (o *ImageSourceGitSpec) SetCredentialsSecretRef(v string) {
	o.CredentialsSecretRef = &v
}

func (o ImageSourceGitSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageSourceGitSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Repo) {
		toSerialize["repo"] = o.Repo
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.CredentialsSecretRef) {
		toSerialize["credentialsSecretRef"] = o.CredentialsSecretRef
	}
	return toSerialize, nil
}

type NullableImageSourceGitSpec struct {
	value *ImageSourceGitSpec
	isSet bool
}

func (v NullableImageSourceGitSpec) Get() *ImageSourceGitSpec {
	return v.value
}

func (v *NullableImageSourceGitSpec) Set(val *ImageSourceGitSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableImageSourceGitSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableImageSourceGitSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageSourceGitSpec(val *ImageSourceGitSpec) *NullableImageSourceGitSpec {
	return &NullableImageSourceGitSpec{value: val, isSet: true}
}

func (v NullableImageSourceGitSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageSourceGitSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
