/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BuildpackBuildOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildpackBuildOptions{}

// BuildpackBuildOptions struct for BuildpackBuildOptions
type BuildpackBuildOptions struct {
	Builder *string `json:"builder,omitempty"`
}

// NewBuildpackBuildOptions instantiates a new BuildpackBuildOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildpackBuildOptions() *BuildpackBuildOptions {
	this := BuildpackBuildOptions{}
	return &this
}

// NewBuildpackBuildOptionsWithDefaults instantiates a new BuildpackBuildOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildpackBuildOptionsWithDefaults() *BuildpackBuildOptions {
	this := BuildpackBuildOptions{}
	return &this
}

// GetBuilder returns the Builder field value if set, zero value otherwise.
func (o *BuildpackBuildOptions) GetBuilder() string {
	if o == nil || IsNil(o.Builder) {
		var ret string
		return ret
	}
	return *o.Builder
}

// GetBuilderOk returns a tuple with the Builder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildpackBuildOptions) GetBuilderOk() (*string, bool) {
	if o == nil || IsNil(o.Builder) {
		return nil, false
	}
	return o.Builder, true
}

// HasBuilder returns a boolean if a field has been set.
func (o *BuildpackBuildOptions) HasBuilder() bool {
	if o != nil && !IsNil(o.Builder) {
		return true
	}

	return false
}

// SetBuilder gets a reference to the given string and assigns it to the Builder field.
func (o *BuildpackBuildOptions) SetBuilder(v string) {
	o.Builder = &v
}

func (o BuildpackBuildOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildpackBuildOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Builder) {
		toSerialize["builder"] = o.Builder
	}
	return toSerialize, nil
}

type NullableBuildpackBuildOptions struct {
	value *BuildpackBuildOptions
	isSet bool
}

func (v NullableBuildpackBuildOptions) Get() *BuildpackBuildOptions {
	return v.value
}

func (v *NullableBuildpackBuildOptions) Set(val *BuildpackBuildOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildpackBuildOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildpackBuildOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildpackBuildOptions(val *BuildpackBuildOptions) *NullableBuildpackBuildOptions {
	return &NullableBuildpackBuildOptions{value: val, isSet: true}
}

func (v NullableBuildpackBuildOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildpackBuildOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
