/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ImageSourcePromotionSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageSourcePromotionSpec{}

// ImageSourcePromotionSpec struct for ImageSourcePromotionSpec
type ImageSourcePromotionSpec struct {
	Upstream     *ImageSourceUpstreamSpec `json:"upstream,omitempty"`
	AutoPromote  *bool                    `json:"autoPromote,omitempty"`
	PinnedDigest *string                  `json:"pinnedDigest,omitempty"`
}

// NewImageSourcePromotionSpec instantiates a new ImageSourcePromotionSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageSourcePromotionSpec() *ImageSourcePromotionSpec {
	this := ImageSourcePromotionSpec{}
	return &this
}

// NewImageSourcePromotionSpecWithDefaults instantiates a new ImageSourcePromotionSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageSourcePromotionSpecWithDefaults() *ImageSourcePromotionSpec {
	this := ImageSourcePromotionSpec{}
	return &this
}

// GetUpstream returns the Upstream field value if set, zero value otherwise.
func (o *ImageSourcePromotionSpec) GetUpstream() ImageSourceUpstreamSpec {
	if o == nil || IsNil(o.Upstream) {
		var ret ImageSourceUpstreamSpec
		return ret
	}
	return *o.Upstream
}

// GetUpstreamOk returns a tuple with the Upstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourcePromotionSpec) GetUpstreamOk() (*ImageSourceUpstreamSpec, bool) {
	if o == nil || IsNil(o.Upstream) {
		return nil, false
	}
	return o.Upstream, true
}

// HasUpstream returns a boolean if a field has been set.
func (o *ImageSourcePromotionSpec) HasUpstream() bool {
	if o != nil && !IsNil(o.Upstream) {
		return true
	}

	return false
}

// SetUpstream gets a reference to the given ImageSourceUpstreamSpec and assigns it to the Upstream field.
func (o *ImageSourcePromotionSpec) SetUpstream(v ImageSourceUpstreamSpec) {
	o.Upstream = &v
}

// GetAutoPromote returns the AutoPromote field value if set, zero value otherwise.
func (o *ImageSourcePromotionSpec) GetAutoPromote() bool {
	if o == nil || IsNil(o.AutoPromote) {
		var ret bool
		return ret
	}
	return *o.AutoPromote
}

// GetAutoPromoteOk returns a tuple with the AutoPromote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourcePromotionSpec) GetAutoPromoteOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoPromote) {
		return nil, false
	}
	return o.AutoPromote, true
}

// HasAutoPromote returns a boolean if a field has been set.
func (o *ImageSourcePromotionSpec) HasAutoPromote() bool {
	if o != nil && !IsNil(o.AutoPromote) {
		return true
	}

	return false
}

// SetAutoPromote gets a reference to the given bool and assigns it to the AutoPromote field.
func (o *ImageSourcePromotionSpec) SetAutoPromote(v bool) {
	o.AutoPromote = &v
}

// GetPinnedDigest returns the PinnedDigest field value if set, zero value otherwise.
func (o *ImageSourcePromotionSpec) GetPinnedDigest() string {
	if o == nil || IsNil(o.PinnedDigest) {
		var ret string
		return ret
	}
	return *o.PinnedDigest
}

// GetPinnedDigestOk returns a tuple with the PinnedDigest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourcePromotionSpec) GetPinnedDigestOk() (*string, bool) {
	if o == nil || IsNil(o.PinnedDigest) {
		return nil, false
	}
	return o.PinnedDigest, true
}

// HasPinnedDigest returns a boolean if a field has been set.
func (o *ImageSourcePromotionSpec) HasPinnedDigest() bool {
	if o != nil && !IsNil(o.PinnedDigest) {
		return true
	}

	return false
}

// SetPinnedDigest gets a reference to the given string and assigns it to the PinnedDigest field.
func (o *ImageSourcePromotionSpec) SetPinnedDigest(v string) {
	o.PinnedDigest = &v
}

func (o ImageSourcePromotionSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageSourcePromotionSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Upstream) {
		toSerialize["upstream"] = o.Upstream
	}
	if !IsNil(o.AutoPromote) {
		toSerialize["autoPromote"] = o.AutoPromote
	}
	if !IsNil(o.PinnedDigest) {
		toSerialize["pinnedDigest"] = o.PinnedDigest
	}
	return toSerialize, nil
}

type NullableImageSourcePromotionSpec struct {
	value *ImageSourcePromotionSpec
	isSet bool
}

func (v NullableImageSourcePromotionSpec) Get() *ImageSourcePromotionSpec {
	return v.value
}

func (v *NullableImageSourcePromotionSpec) Set(val *ImageSourcePromotionSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableImageSourcePromotionSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableImageSourcePromotionSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageSourcePromotionSpec(val *ImageSourcePromotionSpec) *NullableImageSourcePromotionSpec {
	return &NullableImageSourcePromotionSpec{value: val, isSet: true}
}

func (v NullableImageSourcePromotionSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageSourcePromotionSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
