/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SourceBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceBase{}

// SourceBase struct for SourceBase
type SourceBase struct {
	Type string `json:"type"`
	// Polling interval, e.g. '5m'. '0' disables polling.
	PollInterval   *string `json:"pollInterval,omitempty"`
	WebhookEnabled *bool   `json:"webhookEnabled,omitempty"`
}

type _SourceBase SourceBase

// NewSourceBase instantiates a new SourceBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceBase(type_ string) *SourceBase {
	this := SourceBase{}
	this.Type = type_
	return &this
}

// NewSourceBaseWithDefaults instantiates a new SourceBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceBaseWithDefaults() *SourceBase {
	this := SourceBase{}
	return &this
}

// GetType returns the Type field value
func (o *SourceBase) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SourceBase) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SourceBase) SetType(v string) {
	o.Type = v
}

// GetPollInterval returns the PollInterval field value if set, zero value otherwise.
func (o *SourceBase) GetPollInterval() string {
	if o == nil || IsNil(o.PollInterval) {
		var ret string
		return ret
	}
	return *o.PollInterval
}

// GetPollIntervalOk returns a tuple with the PollInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceBase) GetPollIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.PollInterval) {
		return nil, false
	}
	return o.PollInterval, true
}

// HasPollInterval returns a boolean if a field has been set.
func (o *SourceBase) HasPollInterval() bool {
	if o != nil && !IsNil(o.PollInterval) {
		return true
	}

	return false
}

// SetPollInterval gets a reference to the given string and assigns it to the PollInterval field.
func (o *SourceBase) SetPollInterval(v string) {
	o.PollInterval = &v
}

// GetWebhookEnabled returns the WebhookEnabled field value if set, zero value otherwise.
func (o *SourceBase) GetWebhookEnabled() bool {
	if o == nil || IsNil(o.WebhookEnabled) {
		var ret bool
		return ret
	}
	return *o.WebhookEnabled
}

// GetWebhookEnabledOk returns a tuple with the WebhookEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceBase) GetWebhookEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WebhookEnabled) {
		return nil, false
	}
	return o.WebhookEnabled, true
}

// HasWebhookEnabled returns a boolean if a field has been set.
func (o *SourceBase) HasWebhookEnabled() bool {
	if o != nil && !IsNil(o.WebhookEnabled) {
		return true
	}

	return false
}

// SetWebhookEnabled gets a reference to the given bool and assigns it to the WebhookEnabled field.
func (o *SourceBase) SetWebhookEnabled(v bool) {
	o.WebhookEnabled = &v
}

func (o SourceBase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.PollInterval) {
		toSerialize["pollInterval"] = o.PollInterval
	}
	if !IsNil(o.WebhookEnabled) {
		toSerialize["webhookEnabled"] = o.WebhookEnabled
	}
	return toSerialize, nil
}

func (o *SourceBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceBase := _SourceBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSourceBase)

	if err != nil {
		return err
	}

	*o = SourceBase(varSourceBase)

	return err
}

type NullableSourceBase struct {
	value *SourceBase
	isSet bool
}

func (v NullableSourceBase) Get() *SourceBase {
	return v.value
}

func (v *NullableSourceBase) Set(val *SourceBase) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceBase) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceBase(val *SourceBase) *NullableSourceBase {
	return &NullableSourceBase{value: val, isSet: true}
}

func (v NullableSourceBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
