/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentRequest{}

// CreateEnvironmentRequest struct for CreateEnvironmentRequest
type CreateEnvironmentRequest struct {
	Name string `json:"name"`
	ProjectSlug string `json:"projectSlug"`
	Description *string `json:"description,omitempty"`
}

type _CreateEnvironmentRequest CreateEnvironmentRequest

// NewCreateEnvironmentRequest instantiates a new CreateEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentRequest(name string, projectSlug string) *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	this.Name = name
	this.ProjectSlug = projectSlug
	return &this
}

// NewCreateEnvironmentRequestWithDefaults instantiates a new CreateEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentRequestWithDefaults() *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateEnvironmentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEnvironmentRequest) SetName(v string) {
	o.Name = v
}

// GetProjectSlug returns the ProjectSlug field value
func (o *CreateEnvironmentRequest) GetProjectSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectSlug
}

// GetProjectSlugOk returns a tuple with the ProjectSlug field value
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetProjectSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectSlug, true
}

// SetProjectSlug sets field value
func (o *CreateEnvironmentRequest) SetProjectSlug(v string) {
	o.ProjectSlug = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateEnvironmentRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateEnvironmentRequest) SetDescription(v string) {
	o.Description = &v
}

func (o CreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["projectSlug"] = o.ProjectSlug
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CreateEnvironmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"projectSlug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEnvironmentRequest := _CreateEnvironmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEnvironmentRequest)

	if err != nil {
		return err
	}

	*o = CreateEnvironmentRequest(varCreateEnvironmentRequest)

	return err
}

type NullableCreateEnvironmentRequest struct {
	value *CreateEnvironmentRequest
	isSet bool
}

func (v NullableCreateEnvironmentRequest) Get() *CreateEnvironmentRequest {
	return v.value
}

func (v *NullableCreateEnvironmentRequest) Set(val *CreateEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentRequest(val *CreateEnvironmentRequest) *NullableCreateEnvironmentRequest {
	return &NullableCreateEnvironmentRequest{value: val, isSet: true}
}

func (v NullableCreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


