/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PodCpuUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PodCpuUsage{}

// PodCpuUsage struct for PodCpuUsage
type PodCpuUsage struct {
	UsedMillicores  *int64 `json:"usedMillicores,omitempty"`
	LimitMillicores *int64 `json:"limitMillicores,omitempty"`
}

// NewPodCpuUsage instantiates a new PodCpuUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPodCpuUsage() *PodCpuUsage {
	this := PodCpuUsage{}
	return &this
}

// NewPodCpuUsageWithDefaults instantiates a new PodCpuUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPodCpuUsageWithDefaults() *PodCpuUsage {
	this := PodCpuUsage{}
	return &this
}

// GetUsedMillicores returns the UsedMillicores field value if set, zero value otherwise.
func (o *PodCpuUsage) GetUsedMillicores() int64 {
	if o == nil || IsNil(o.UsedMillicores) {
		var ret int64
		return ret
	}
	return *o.UsedMillicores
}

// GetUsedMillicoresOk returns a tuple with the UsedMillicores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodCpuUsage) GetUsedMillicoresOk() (*int64, bool) {
	if o == nil || IsNil(o.UsedMillicores) {
		return nil, false
	}
	return o.UsedMillicores, true
}

// HasUsedMillicores returns a boolean if a field has been set.
func (o *PodCpuUsage) HasUsedMillicores() bool {
	if o != nil && !IsNil(o.UsedMillicores) {
		return true
	}

	return false
}

// SetUsedMillicores gets a reference to the given int64 and assigns it to the UsedMillicores field.
func (o *PodCpuUsage) SetUsedMillicores(v int64) {
	o.UsedMillicores = &v
}

// GetLimitMillicores returns the LimitMillicores field value if set, zero value otherwise.
func (o *PodCpuUsage) GetLimitMillicores() int64 {
	if o == nil || IsNil(o.LimitMillicores) {
		var ret int64
		return ret
	}
	return *o.LimitMillicores
}

// GetLimitMillicoresOk returns a tuple with the LimitMillicores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodCpuUsage) GetLimitMillicoresOk() (*int64, bool) {
	if o == nil || IsNil(o.LimitMillicores) {
		return nil, false
	}
	return o.LimitMillicores, true
}

// HasLimitMillicores returns a boolean if a field has been set.
func (o *PodCpuUsage) HasLimitMillicores() bool {
	if o != nil && !IsNil(o.LimitMillicores) {
		return true
	}

	return false
}

// SetLimitMillicores gets a reference to the given int64 and assigns it to the LimitMillicores field.
func (o *PodCpuUsage) SetLimitMillicores(v int64) {
	o.LimitMillicores = &v
}

func (o PodCpuUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PodCpuUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UsedMillicores) {
		toSerialize["usedMillicores"] = o.UsedMillicores
	}
	if !IsNil(o.LimitMillicores) {
		toSerialize["limitMillicores"] = o.LimitMillicores
	}
	return toSerialize, nil
}

type NullablePodCpuUsage struct {
	value *PodCpuUsage
	isSet bool
}

func (v NullablePodCpuUsage) Get() *PodCpuUsage {
	return v.value
}

func (v *NullablePodCpuUsage) Set(val *PodCpuUsage) {
	v.value = val
	v.isSet = true
}

func (v NullablePodCpuUsage) IsSet() bool {
	return v.isSet
}

func (v *NullablePodCpuUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePodCpuUsage(val *PodCpuUsage) *NullablePodCpuUsage {
	return &NullablePodCpuUsage{value: val, isSet: true}
}

func (v NullablePodCpuUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePodCpuUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
