/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the WebhookDelivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDelivery{}

// WebhookDelivery struct for WebhookDelivery
type WebhookDelivery struct {
	Id *string `json:"id,omitempty"`
	WebhookId *string `json:"webhookId,omitempty"`
	Event *string `json:"event,omitempty"`
	Status *string `json:"status,omitempty"`
	ResponseCode *int32 `json:"responseCode,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

// NewWebhookDelivery instantiates a new WebhookDelivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDelivery() *WebhookDelivery {
	this := WebhookDelivery{}
	return &this
}

// NewWebhookDeliveryWithDefaults instantiates a new WebhookDelivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryWithDefaults() *WebhookDelivery {
	this := WebhookDelivery{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WebhookDelivery) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WebhookDelivery) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WebhookDelivery) SetId(v string) {
	o.Id = &v
}

// GetWebhookId returns the WebhookId field value if set, zero value otherwise.
func (o *WebhookDelivery) GetWebhookId() string {
	if o == nil || IsNil(o.WebhookId) {
		var ret string
		return ret
	}
	return *o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetWebhookIdOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookId) {
		return nil, false
	}
	return o.WebhookId, true
}

// HasWebhookId returns a boolean if a field has been set.
func (o *WebhookDelivery) HasWebhookId() bool {
	if o != nil && !IsNil(o.WebhookId) {
		return true
	}

	return false
}

// SetWebhookId gets a reference to the given string and assigns it to the WebhookId field.
func (o *WebhookDelivery) SetWebhookId(v string) {
	o.WebhookId = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *WebhookDelivery) GetEvent() string {
	if o == nil || IsNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetEventOk() (*string, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *WebhookDelivery) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *WebhookDelivery) SetEvent(v string) {
	o.Event = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WebhookDelivery) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WebhookDelivery) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WebhookDelivery) SetStatus(v string) {
	o.Status = &v
}

// GetResponseCode returns the ResponseCode field value if set, zero value otherwise.
func (o *WebhookDelivery) GetResponseCode() int32 {
	if o == nil || IsNil(o.ResponseCode) {
		var ret int32
		return ret
	}
	return *o.ResponseCode
}

// GetResponseCodeOk returns a tuple with the ResponseCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetResponseCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ResponseCode) {
		return nil, false
	}
	return o.ResponseCode, true
}

// HasResponseCode returns a boolean if a field has been set.
func (o *WebhookDelivery) HasResponseCode() bool {
	if o != nil && !IsNil(o.ResponseCode) {
		return true
	}

	return false
}

// SetResponseCode gets a reference to the given int32 and assigns it to the ResponseCode field.
func (o *WebhookDelivery) SetResponseCode(v int32) {
	o.ResponseCode = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WebhookDelivery) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WebhookDelivery) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WebhookDelivery) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o WebhookDelivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDelivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.WebhookId) {
		toSerialize["webhookId"] = o.WebhookId
	}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ResponseCode) {
		toSerialize["responseCode"] = o.ResponseCode
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableWebhookDelivery struct {
	value *WebhookDelivery
	isSet bool
}

func (v NullableWebhookDelivery) Get() *WebhookDelivery {
	return v.value
}

func (v *NullableWebhookDelivery) Set(val *WebhookDelivery) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDelivery(val *WebhookDelivery) *NullableWebhookDelivery {
	return &NullableWebhookDelivery{value: val, isSet: true}
}

func (v NullableWebhookDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


