/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WorkspaceMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceMember{}

// WorkspaceMember struct for WorkspaceMember
type WorkspaceMember struct {
	UserId *string `json:"userId,omitempty"`
	Email *string `json:"email,omitempty"`
	Role *string `json:"role,omitempty"`
}

// NewWorkspaceMember instantiates a new WorkspaceMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceMember() *WorkspaceMember {
	this := WorkspaceMember{}
	return &this
}

// NewWorkspaceMemberWithDefaults instantiates a new WorkspaceMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceMemberWithDefaults() *WorkspaceMember {
	this := WorkspaceMember{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *WorkspaceMember) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceMember) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *WorkspaceMember) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *WorkspaceMember) SetUserId(v string) {
	o.UserId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *WorkspaceMember) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceMember) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *WorkspaceMember) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *WorkspaceMember) SetEmail(v string) {
	o.Email = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *WorkspaceMember) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceMember) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *WorkspaceMember) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *WorkspaceMember) SetRole(v string) {
	o.Role = &v
}

func (o WorkspaceMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableWorkspaceMember struct {
	value *WorkspaceMember
	isSet bool
}

func (v NullableWorkspaceMember) Get() *WorkspaceMember {
	return v.value
}

func (v *NullableWorkspaceMember) Set(val *WorkspaceMember) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceMember) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceMember(val *WorkspaceMember) *NullableWorkspaceMember {
	return &NullableWorkspaceMember{value: val, isSet: true}
}

func (v NullableWorkspaceMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


