/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateGroupMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGroupMappingRequest{}

// UpdateGroupMappingRequest struct for UpdateGroupMappingRequest
type UpdateGroupMappingRequest struct {
	Role *string `json:"role,omitempty"`
}

// NewUpdateGroupMappingRequest instantiates a new UpdateGroupMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGroupMappingRequest() *UpdateGroupMappingRequest {
	this := UpdateGroupMappingRequest{}
	return &this
}

// NewUpdateGroupMappingRequestWithDefaults instantiates a new UpdateGroupMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGroupMappingRequestWithDefaults() *UpdateGroupMappingRequest {
	this := UpdateGroupMappingRequest{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UpdateGroupMappingRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGroupMappingRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UpdateGroupMappingRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UpdateGroupMappingRequest) SetRole(v string) {
	o.Role = &v
}

func (o UpdateGroupMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGroupMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableUpdateGroupMappingRequest struct {
	value *UpdateGroupMappingRequest
	isSet bool
}

func (v NullableUpdateGroupMappingRequest) Get() *UpdateGroupMappingRequest {
	return v.value
}

func (v *NullableUpdateGroupMappingRequest) Set(val *UpdateGroupMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGroupMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGroupMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGroupMappingRequest(val *UpdateGroupMappingRequest) *NullableUpdateGroupMappingRequest {
	return &NullableUpdateGroupMappingRequest{value: val, isSet: true}
}

func (v NullableUpdateGroupMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGroupMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
