/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the WorkspaceInviteCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceInviteCode{}

// WorkspaceInviteCode struct for WorkspaceInviteCode
type WorkspaceInviteCode struct {
	Id        *string    `json:"id,omitempty"`
	Code      *string    `json:"code,omitempty"`
	Role      *string    `json:"role,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	MaxUses   *int32     `json:"maxUses,omitempty"`
	UseCount  *int32     `json:"useCount,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	CreatedBy *string    `json:"createdBy,omitempty"`
}

// NewWorkspaceInviteCode instantiates a new WorkspaceInviteCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceInviteCode() *WorkspaceInviteCode {
	this := WorkspaceInviteCode{}
	return &this
}

// NewWorkspaceInviteCodeWithDefaults instantiates a new WorkspaceInviteCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceInviteCodeWithDefaults() *WorkspaceInviteCode {
	this := WorkspaceInviteCode{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WorkspaceInviteCode) SetId(v string) {
	o.Id = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *WorkspaceInviteCode) SetCode(v string) {
	o.Code = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *WorkspaceInviteCode) SetRole(v string) {
	o.Role = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *WorkspaceInviteCode) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetMaxUses returns the MaxUses field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetMaxUses() int32 {
	if o == nil || IsNil(o.MaxUses) {
		var ret int32
		return ret
	}
	return *o.MaxUses
}

// GetMaxUsesOk returns a tuple with the MaxUses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetMaxUsesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxUses) {
		return nil, false
	}
	return o.MaxUses, true
}

// HasMaxUses returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasMaxUses() bool {
	if o != nil && !IsNil(o.MaxUses) {
		return true
	}

	return false
}

// SetMaxUses gets a reference to the given int32 and assigns it to the MaxUses field.
func (o *WorkspaceInviteCode) SetMaxUses(v int32) {
	o.MaxUses = &v
}

// GetUseCount returns the UseCount field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetUseCount() int32 {
	if o == nil || IsNil(o.UseCount) {
		var ret int32
		return ret
	}
	return *o.UseCount
}

// GetUseCountOk returns a tuple with the UseCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetUseCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UseCount) {
		return nil, false
	}
	return o.UseCount, true
}

// HasUseCount returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasUseCount() bool {
	if o != nil && !IsNil(o.UseCount) {
		return true
	}

	return false
}

// SetUseCount gets a reference to the given int32 and assigns it to the UseCount field.
func (o *WorkspaceInviteCode) SetUseCount(v int32) {
	o.UseCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WorkspaceInviteCode) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *WorkspaceInviteCode) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInviteCode) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *WorkspaceInviteCode) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *WorkspaceInviteCode) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

func (o WorkspaceInviteCode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceInviteCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.MaxUses) {
		toSerialize["maxUses"] = o.MaxUses
	}
	if !IsNil(o.UseCount) {
		toSerialize["useCount"] = o.UseCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	return toSerialize, nil
}

type NullableWorkspaceInviteCode struct {
	value *WorkspaceInviteCode
	isSet bool
}

func (v NullableWorkspaceInviteCode) Get() *WorkspaceInviteCode {
	return v.value
}

func (v *NullableWorkspaceInviteCode) Set(val *WorkspaceInviteCode) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceInviteCode) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceInviteCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceInviteCode(val *WorkspaceInviteCode) *NullableWorkspaceInviteCode {
	return &NullableWorkspaceInviteCode{value: val, isSet: true}
}

func (v NullableWorkspaceInviteCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceInviteCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
