/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BuildDetectionJobCreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildDetectionJobCreated{}

// BuildDetectionJobCreated struct for BuildDetectionJobCreated
type BuildDetectionJobCreated struct {
	JobId *string `json:"jobId,omitempty"`
}

// NewBuildDetectionJobCreated instantiates a new BuildDetectionJobCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildDetectionJobCreated() *BuildDetectionJobCreated {
	this := BuildDetectionJobCreated{}
	return &this
}

// NewBuildDetectionJobCreatedWithDefaults instantiates a new BuildDetectionJobCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildDetectionJobCreatedWithDefaults() *BuildDetectionJobCreated {
	this := BuildDetectionJobCreated{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *BuildDetectionJobCreated) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDetectionJobCreated) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *BuildDetectionJobCreated) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *BuildDetectionJobCreated) SetJobId(v string) {
	o.JobId = &v
}

func (o BuildDetectionJobCreated) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildDetectionJobCreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	return toSerialize, nil
}

type NullableBuildDetectionJobCreated struct {
	value *BuildDetectionJobCreated
	isSet bool
}

func (v NullableBuildDetectionJobCreated) Get() *BuildDetectionJobCreated {
	return v.value
}

func (v *NullableBuildDetectionJobCreated) Set(val *BuildDetectionJobCreated) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildDetectionJobCreated) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildDetectionJobCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildDetectionJobCreated(val *BuildDetectionJobCreated) *NullableBuildDetectionJobCreated {
	return &NullableBuildDetectionJobCreated{value: val, isSet: true}
}

func (v NullableBuildDetectionJobCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildDetectionJobCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
