/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PodMemoryUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PodMemoryUsage{}

// PodMemoryUsage struct for PodMemoryUsage
type PodMemoryUsage struct {
	UsedBytes  *int64 `json:"usedBytes,omitempty"`
	LimitBytes *int64 `json:"limitBytes,omitempty"`
}

// NewPodMemoryUsage instantiates a new PodMemoryUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPodMemoryUsage() *PodMemoryUsage {
	this := PodMemoryUsage{}
	return &this
}

// NewPodMemoryUsageWithDefaults instantiates a new PodMemoryUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPodMemoryUsageWithDefaults() *PodMemoryUsage {
	this := PodMemoryUsage{}
	return &this
}

// GetUsedBytes returns the UsedBytes field value if set, zero value otherwise.
func (o *PodMemoryUsage) GetUsedBytes() int64 {
	if o == nil || IsNil(o.UsedBytes) {
		var ret int64
		return ret
	}
	return *o.UsedBytes
}

// GetUsedBytesOk returns a tuple with the UsedBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodMemoryUsage) GetUsedBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.UsedBytes) {
		return nil, false
	}
	return o.UsedBytes, true
}

// HasUsedBytes returns a boolean if a field has been set.
func (o *PodMemoryUsage) HasUsedBytes() bool {
	if o != nil && !IsNil(o.UsedBytes) {
		return true
	}

	return false
}

// SetUsedBytes gets a reference to the given int64 and assigns it to the UsedBytes field.
func (o *PodMemoryUsage) SetUsedBytes(v int64) {
	o.UsedBytes = &v
}

// GetLimitBytes returns the LimitBytes field value if set, zero value otherwise.
func (o *PodMemoryUsage) GetLimitBytes() int64 {
	if o == nil || IsNil(o.LimitBytes) {
		var ret int64
		return ret
	}
	return *o.LimitBytes
}

// GetLimitBytesOk returns a tuple with the LimitBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodMemoryUsage) GetLimitBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.LimitBytes) {
		return nil, false
	}
	return o.LimitBytes, true
}

// HasLimitBytes returns a boolean if a field has been set.
func (o *PodMemoryUsage) HasLimitBytes() bool {
	if o != nil && !IsNil(o.LimitBytes) {
		return true
	}

	return false
}

// SetLimitBytes gets a reference to the given int64 and assigns it to the LimitBytes field.
func (o *PodMemoryUsage) SetLimitBytes(v int64) {
	o.LimitBytes = &v
}

func (o PodMemoryUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PodMemoryUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UsedBytes) {
		toSerialize["usedBytes"] = o.UsedBytes
	}
	if !IsNil(o.LimitBytes) {
		toSerialize["limitBytes"] = o.LimitBytes
	}
	return toSerialize, nil
}

type NullablePodMemoryUsage struct {
	value *PodMemoryUsage
	isSet bool
}

func (v NullablePodMemoryUsage) Get() *PodMemoryUsage {
	return v.value
}

func (v *NullablePodMemoryUsage) Set(val *PodMemoryUsage) {
	v.value = val
	v.isSet = true
}

func (v NullablePodMemoryUsage) IsSet() bool {
	return v.isSet
}

func (v *NullablePodMemoryUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePodMemoryUsage(val *PodMemoryUsage) *NullablePodMemoryUsage {
	return &NullablePodMemoryUsage{value: val, isSet: true}
}

func (v NullablePodMemoryUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePodMemoryUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
