/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PagedDeploymentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagedDeploymentResponse{}

// PagedDeploymentResponse struct for PagedDeploymentResponse
type PagedDeploymentResponse struct {
	Content []Deployment `json:"content,omitempty"`
	Page *int32 `json:"page,omitempty"`
	Size *int32 `json:"size,omitempty"`
	TotalElements *int64 `json:"totalElements,omitempty"`
	TotalPages *int32 `json:"totalPages,omitempty"`
}

// NewPagedDeploymentResponse instantiates a new PagedDeploymentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagedDeploymentResponse() *PagedDeploymentResponse {
	this := PagedDeploymentResponse{}
	return &this
}

// NewPagedDeploymentResponseWithDefaults instantiates a new PagedDeploymentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagedDeploymentResponseWithDefaults() *PagedDeploymentResponse {
	this := PagedDeploymentResponse{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *PagedDeploymentResponse) GetContent() []Deployment {
	if o == nil || IsNil(o.Content) {
		var ret []Deployment
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedDeploymentResponse) GetContentOk() ([]Deployment, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *PagedDeploymentResponse) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []Deployment and assigns it to the Content field.
func (o *PagedDeploymentResponse) SetContent(v []Deployment) {
	o.Content = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PagedDeploymentResponse) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedDeploymentResponse) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PagedDeploymentResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *PagedDeploymentResponse) SetPage(v int32) {
	o.Page = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PagedDeploymentResponse) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedDeploymentResponse) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PagedDeploymentResponse) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *PagedDeploymentResponse) SetSize(v int32) {
	o.Size = &v
}

// GetTotalElements returns the TotalElements field value if set, zero value otherwise.
func (o *PagedDeploymentResponse) GetTotalElements() int64 {
	if o == nil || IsNil(o.TotalElements) {
		var ret int64
		return ret
	}
	return *o.TotalElements
}

// GetTotalElementsOk returns a tuple with the TotalElements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedDeploymentResponse) GetTotalElementsOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalElements) {
		return nil, false
	}
	return o.TotalElements, true
}

// HasTotalElements returns a boolean if a field has been set.
func (o *PagedDeploymentResponse) HasTotalElements() bool {
	if o != nil && !IsNil(o.TotalElements) {
		return true
	}

	return false
}

// SetTotalElements gets a reference to the given int64 and assigns it to the TotalElements field.
func (o *PagedDeploymentResponse) SetTotalElements(v int64) {
	o.TotalElements = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *PagedDeploymentResponse) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedDeploymentResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *PagedDeploymentResponse) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *PagedDeploymentResponse) SetTotalPages(v int32) {
	o.TotalPages = &v
}

func (o PagedDeploymentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagedDeploymentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.TotalElements) {
		toSerialize["totalElements"] = o.TotalElements
	}
	if !IsNil(o.TotalPages) {
		toSerialize["totalPages"] = o.TotalPages
	}
	return toSerialize, nil
}

type NullablePagedDeploymentResponse struct {
	value *PagedDeploymentResponse
	isSet bool
}

func (v NullablePagedDeploymentResponse) Get() *PagedDeploymentResponse {
	return v.value
}

func (v *NullablePagedDeploymentResponse) Set(val *PagedDeploymentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePagedDeploymentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePagedDeploymentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagedDeploymentResponse(val *PagedDeploymentResponse) *NullablePagedDeploymentResponse {
	return &NullablePagedDeploymentResponse{value: val, isSet: true}
}

func (v NullablePagedDeploymentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagedDeploymentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


