/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the LinkStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkStatus{}

// LinkStatus struct for LinkStatus
type LinkStatus struct {
	Resource     *string    `json:"resource,omitempty"`
	Status       *string    `json:"status,omitempty"`
	LastSyncTime *time.Time `json:"lastSyncTime,omitempty"`
}

// NewLinkStatus instantiates a new LinkStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkStatus() *LinkStatus {
	this := LinkStatus{}
	return &this
}

// NewLinkStatusWithDefaults instantiates a new LinkStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkStatusWithDefaults() *LinkStatus {
	this := LinkStatus{}
	return &this
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *LinkStatus) GetResource() string {
	if o == nil || IsNil(o.Resource) {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStatus) GetResourceOk() (*string, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *LinkStatus) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *LinkStatus) SetResource(v string) {
	o.Resource = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LinkStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LinkStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *LinkStatus) SetStatus(v string) {
	o.Status = &v
}

// GetLastSyncTime returns the LastSyncTime field value if set, zero value otherwise.
func (o *LinkStatus) GetLastSyncTime() time.Time {
	if o == nil || IsNil(o.LastSyncTime) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncTime
}

// GetLastSyncTimeOk returns a tuple with the LastSyncTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkStatus) GetLastSyncTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSyncTime) {
		return nil, false
	}
	return o.LastSyncTime, true
}

// HasLastSyncTime returns a boolean if a field has been set.
func (o *LinkStatus) HasLastSyncTime() bool {
	if o != nil && !IsNil(o.LastSyncTime) {
		return true
	}

	return false
}

// SetLastSyncTime gets a reference to the given time.Time and assigns it to the LastSyncTime field.
func (o *LinkStatus) SetLastSyncTime(v time.Time) {
	o.LastSyncTime = &v
}

func (o LinkStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.LastSyncTime) {
		toSerialize["lastSyncTime"] = o.LastSyncTime
	}
	return toSerialize, nil
}

type NullableLinkStatus struct {
	value *LinkStatus
	isSet bool
}

func (v NullableLinkStatus) Get() *LinkStatus {
	return v.value
}

func (v *NullableLinkStatus) Set(val *LinkStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkStatus(val *LinkStatus) *NullableLinkStatus {
	return &NullableLinkStatus{value: val, isSet: true}
}

func (v NullableLinkStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
