/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RedeemInviteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedeemInviteRequest{}

// RedeemInviteRequest struct for RedeemInviteRequest
type RedeemInviteRequest struct {
	Code string `json:"code"`
}

type _RedeemInviteRequest RedeemInviteRequest

// NewRedeemInviteRequest instantiates a new RedeemInviteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedeemInviteRequest(code string) *RedeemInviteRequest {
	this := RedeemInviteRequest{}
	this.Code = code
	return &this
}

// NewRedeemInviteRequestWithDefaults instantiates a new RedeemInviteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedeemInviteRequestWithDefaults() *RedeemInviteRequest {
	this := RedeemInviteRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *RedeemInviteRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *RedeemInviteRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *RedeemInviteRequest) SetCode(v string) {
	o.Code = v
}

func (o RedeemInviteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedeemInviteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

func (o *RedeemInviteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRedeemInviteRequest := _RedeemInviteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRedeemInviteRequest)

	if err != nil {
		return err
	}

	*o = RedeemInviteRequest(varRedeemInviteRequest)

	return err
}

type NullableRedeemInviteRequest struct {
	value *RedeemInviteRequest
	isSet bool
}

func (v NullableRedeemInviteRequest) Get() *RedeemInviteRequest {
	return v.value
}

func (v *NullableRedeemInviteRequest) Set(val *RedeemInviteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRedeemInviteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRedeemInviteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedeemInviteRequest(val *RedeemInviteRequest) *NullableRedeemInviteRequest {
	return &NullableRedeemInviteRequest{value: val, isSet: true}
}

func (v NullableRedeemInviteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedeemInviteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
