/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SetTargetClusterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetTargetClusterRequest{}

// SetTargetClusterRequest struct for SetTargetClusterRequest
type SetTargetClusterRequest struct {
	ClusterName string `json:"clusterName"`
}

type _SetTargetClusterRequest SetTargetClusterRequest

// NewSetTargetClusterRequest instantiates a new SetTargetClusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetTargetClusterRequest(clusterName string) *SetTargetClusterRequest {
	this := SetTargetClusterRequest{}
	this.ClusterName = clusterName
	return &this
}

// NewSetTargetClusterRequestWithDefaults instantiates a new SetTargetClusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetTargetClusterRequestWithDefaults() *SetTargetClusterRequest {
	this := SetTargetClusterRequest{}
	return &this
}

// GetClusterName returns the ClusterName field value
func (o *SetTargetClusterRequest) GetClusterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterName
}

// GetClusterNameOk returns a tuple with the ClusterName field value
// and a boolean to check if the value has been set.
func (o *SetTargetClusterRequest) GetClusterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterName, true
}

// SetClusterName sets field value
func (o *SetTargetClusterRequest) SetClusterName(v string) {
	o.ClusterName = v
}

func (o SetTargetClusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetTargetClusterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clusterName"] = o.ClusterName
	return toSerialize, nil
}

func (o *SetTargetClusterRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clusterName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetTargetClusterRequest := _SetTargetClusterRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetTargetClusterRequest)

	if err != nil {
		return err
	}

	*o = SetTargetClusterRequest(varSetTargetClusterRequest)

	return err
}

type NullableSetTargetClusterRequest struct {
	value *SetTargetClusterRequest
	isSet bool
}

func (v NullableSetTargetClusterRequest) Get() *SetTargetClusterRequest {
	return v.value
}

func (v *NullableSetTargetClusterRequest) Set(val *SetTargetClusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetTargetClusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetTargetClusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetTargetClusterRequest(val *SetTargetClusterRequest) *NullableSetTargetClusterRequest {
	return &NullableSetTargetClusterRequest{value: val, isSet: true}
}

func (v NullableSetTargetClusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetTargetClusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
