/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ClusterCapacity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterCapacity{}

// ClusterCapacity struct for ClusterCapacity
type ClusterCapacity struct {
	ClusterName            *string `json:"clusterName,omitempty"`
	CpuAvailableMillicores *int64  `json:"cpuAvailableMillicores,omitempty"`
	CpuTotalMillicores     *int64  `json:"cpuTotalMillicores,omitempty"`
	MemoryAvailableBytes   *int64  `json:"memoryAvailableBytes,omitempty"`
	MemoryTotalBytes       *int64  `json:"memoryTotalBytes,omitempty"`
	SchedulableNodes       *int32  `json:"schedulableNodes,omitempty"`
}

// NewClusterCapacity instantiates a new ClusterCapacity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterCapacity() *ClusterCapacity {
	this := ClusterCapacity{}
	return &this
}

// NewClusterCapacityWithDefaults instantiates a new ClusterCapacity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterCapacityWithDefaults() *ClusterCapacity {
	this := ClusterCapacity{}
	return &this
}

// GetClusterName returns the ClusterName field value if set, zero value otherwise.
func (o *ClusterCapacity) GetClusterName() string {
	if o == nil || IsNil(o.ClusterName) {
		var ret string
		return ret
	}
	return *o.ClusterName
}

// GetClusterNameOk returns a tuple with the ClusterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCapacity) GetClusterNameOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterName) {
		return nil, false
	}
	return o.ClusterName, true
}

// HasClusterName returns a boolean if a field has been set.
func (o *ClusterCapacity) HasClusterName() bool {
	if o != nil && !IsNil(o.ClusterName) {
		return true
	}

	return false
}

// SetClusterName gets a reference to the given string and assigns it to the ClusterName field.
func (o *ClusterCapacity) SetClusterName(v string) {
	o.ClusterName = &v
}

// GetCpuAvailableMillicores returns the CpuAvailableMillicores field value if set, zero value otherwise.
func (o *ClusterCapacity) GetCpuAvailableMillicores() int64 {
	if o == nil || IsNil(o.CpuAvailableMillicores) {
		var ret int64
		return ret
	}
	return *o.CpuAvailableMillicores
}

// GetCpuAvailableMillicoresOk returns a tuple with the CpuAvailableMillicores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCapacity) GetCpuAvailableMillicoresOk() (*int64, bool) {
	if o == nil || IsNil(o.CpuAvailableMillicores) {
		return nil, false
	}
	return o.CpuAvailableMillicores, true
}

// HasCpuAvailableMillicores returns a boolean if a field has been set.
func (o *ClusterCapacity) HasCpuAvailableMillicores() bool {
	if o != nil && !IsNil(o.CpuAvailableMillicores) {
		return true
	}

	return false
}

// SetCpuAvailableMillicores gets a reference to the given int64 and assigns it to the CpuAvailableMillicores field.
func (o *ClusterCapacity) SetCpuAvailableMillicores(v int64) {
	o.CpuAvailableMillicores = &v
}

// GetCpuTotalMillicores returns the CpuTotalMillicores field value if set, zero value otherwise.
func (o *ClusterCapacity) GetCpuTotalMillicores() int64 {
	if o == nil || IsNil(o.CpuTotalMillicores) {
		var ret int64
		return ret
	}
	return *o.CpuTotalMillicores
}

// GetCpuTotalMillicoresOk returns a tuple with the CpuTotalMillicores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCapacity) GetCpuTotalMillicoresOk() (*int64, bool) {
	if o == nil || IsNil(o.CpuTotalMillicores) {
		return nil, false
	}
	return o.CpuTotalMillicores, true
}

// HasCpuTotalMillicores returns a boolean if a field has been set.
func (o *ClusterCapacity) HasCpuTotalMillicores() bool {
	if o != nil && !IsNil(o.CpuTotalMillicores) {
		return true
	}

	return false
}

// SetCpuTotalMillicores gets a reference to the given int64 and assigns it to the CpuTotalMillicores field.
func (o *ClusterCapacity) SetCpuTotalMillicores(v int64) {
	o.CpuTotalMillicores = &v
}

// GetMemoryAvailableBytes returns the MemoryAvailableBytes field value if set, zero value otherwise.
func (o *ClusterCapacity) GetMemoryAvailableBytes() int64 {
	if o == nil || IsNil(o.MemoryAvailableBytes) {
		var ret int64
		return ret
	}
	return *o.MemoryAvailableBytes
}

// GetMemoryAvailableBytesOk returns a tuple with the MemoryAvailableBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCapacity) GetMemoryAvailableBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.MemoryAvailableBytes) {
		return nil, false
	}
	return o.MemoryAvailableBytes, true
}

// HasMemoryAvailableBytes returns a boolean if a field has been set.
func (o *ClusterCapacity) HasMemoryAvailableBytes() bool {
	if o != nil && !IsNil(o.MemoryAvailableBytes) {
		return true
	}

	return false
}

// SetMemoryAvailableBytes gets a reference to the given int64 and assigns it to the MemoryAvailableBytes field.
func (o *ClusterCapacity) SetMemoryAvailableBytes(v int64) {
	o.MemoryAvailableBytes = &v
}

// GetMemoryTotalBytes returns the MemoryTotalBytes field value if set, zero value otherwise.
func (o *ClusterCapacity) GetMemoryTotalBytes() int64 {
	if o == nil || IsNil(o.MemoryTotalBytes) {
		var ret int64
		return ret
	}
	return *o.MemoryTotalBytes
}

// GetMemoryTotalBytesOk returns a tuple with the MemoryTotalBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCapacity) GetMemoryTotalBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.MemoryTotalBytes) {
		return nil, false
	}
	return o.MemoryTotalBytes, true
}

// HasMemoryTotalBytes returns a boolean if a field has been set.
func (o *ClusterCapacity) HasMemoryTotalBytes() bool {
	if o != nil && !IsNil(o.MemoryTotalBytes) {
		return true
	}

	return false
}

// SetMemoryTotalBytes gets a reference to the given int64 and assigns it to the MemoryTotalBytes field.
func (o *ClusterCapacity) SetMemoryTotalBytes(v int64) {
	o.MemoryTotalBytes = &v
}

// GetSchedulableNodes returns the SchedulableNodes field value if set, zero value otherwise.
func (o *ClusterCapacity) GetSchedulableNodes() int32 {
	if o == nil || IsNil(o.SchedulableNodes) {
		var ret int32
		return ret
	}
	return *o.SchedulableNodes
}

// GetSchedulableNodesOk returns a tuple with the SchedulableNodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCapacity) GetSchedulableNodesOk() (*int32, bool) {
	if o == nil || IsNil(o.SchedulableNodes) {
		return nil, false
	}
	return o.SchedulableNodes, true
}

// HasSchedulableNodes returns a boolean if a field has been set.
func (o *ClusterCapacity) HasSchedulableNodes() bool {
	if o != nil && !IsNil(o.SchedulableNodes) {
		return true
	}

	return false
}

// SetSchedulableNodes gets a reference to the given int32 and assigns it to the SchedulableNodes field.
func (o *ClusterCapacity) SetSchedulableNodes(v int32) {
	o.SchedulableNodes = &v
}

func (o ClusterCapacity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterCapacity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClusterName) {
		toSerialize["clusterName"] = o.ClusterName
	}
	if !IsNil(o.CpuAvailableMillicores) {
		toSerialize["cpuAvailableMillicores"] = o.CpuAvailableMillicores
	}
	if !IsNil(o.CpuTotalMillicores) {
		toSerialize["cpuTotalMillicores"] = o.CpuTotalMillicores
	}
	if !IsNil(o.MemoryAvailableBytes) {
		toSerialize["memoryAvailableBytes"] = o.MemoryAvailableBytes
	}
	if !IsNil(o.MemoryTotalBytes) {
		toSerialize["memoryTotalBytes"] = o.MemoryTotalBytes
	}
	if !IsNil(o.SchedulableNodes) {
		toSerialize["schedulableNodes"] = o.SchedulableNodes
	}
	return toSerialize, nil
}

type NullableClusterCapacity struct {
	value *ClusterCapacity
	isSet bool
}

func (v NullableClusterCapacity) Get() *ClusterCapacity {
	return v.value
}

func (v *NullableClusterCapacity) Set(val *ClusterCapacity) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterCapacity) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterCapacity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterCapacity(val *ClusterCapacity) *NullableClusterCapacity {
	return &NullableClusterCapacity{value: val, isSet: true}
}

func (v NullableClusterCapacity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterCapacity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
