/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the RegistryConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistryConfig{}

// RegistryConfig struct for RegistryConfig
type RegistryConfig struct {
	Url *string `json:"url,omitempty"`
	CredentialRef *string `json:"credentialRef,omitempty"`
}

// NewRegistryConfig instantiates a new RegistryConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryConfig() *RegistryConfig {
	this := RegistryConfig{}
	return &this
}

// NewRegistryConfigWithDefaults instantiates a new RegistryConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryConfigWithDefaults() *RegistryConfig {
	this := RegistryConfig{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *RegistryConfig) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryConfig) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *RegistryConfig) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *RegistryConfig) SetUrl(v string) {
	o.Url = &v
}

// GetCredentialRef returns the CredentialRef field value if set, zero value otherwise.
func (o *RegistryConfig) GetCredentialRef() string {
	if o == nil || IsNil(o.CredentialRef) {
		var ret string
		return ret
	}
	return *o.CredentialRef
}

// GetCredentialRefOk returns a tuple with the CredentialRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryConfig) GetCredentialRefOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialRef) {
		return nil, false
	}
	return o.CredentialRef, true
}

// HasCredentialRef returns a boolean if a field has been set.
func (o *RegistryConfig) HasCredentialRef() bool {
	if o != nil && !IsNil(o.CredentialRef) {
		return true
	}

	return false
}

// SetCredentialRef gets a reference to the given string and assigns it to the CredentialRef field.
func (o *RegistryConfig) SetCredentialRef(v string) {
	o.CredentialRef = &v
}

func (o RegistryConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistryConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.CredentialRef) {
		toSerialize["credentialRef"] = o.CredentialRef
	}
	return toSerialize, nil
}

type NullableRegistryConfig struct {
	value *RegistryConfig
	isSet bool
}

func (v NullableRegistryConfig) Get() *RegistryConfig {
	return v.value
}

func (v *NullableRegistryConfig) Set(val *RegistryConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryConfig(val *RegistryConfig) *NullableRegistryConfig {
	return &NullableRegistryConfig{value: val, isSet: true}
}

func (v NullableRegistryConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


