/*
AppBahn Platform API

Enterprise PaaS on your own Kubernetes infrastructure.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ImageSourcePoll type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageSourcePoll{}

// ImageSourcePoll struct for ImageSourcePoll
type ImageSourcePoll struct {
	IntervalSeconds             *int32 `json:"intervalSeconds,omitempty"`
	IntervalSecondsAfterWebhook *int32 `json:"intervalSecondsAfterWebhook,omitempty"`
	WebhookFreshnessSeconds     *int32 `json:"webhookFreshnessSeconds,omitempty"`
}

// NewImageSourcePoll instantiates a new ImageSourcePoll object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageSourcePoll() *ImageSourcePoll {
	this := ImageSourcePoll{}
	return &this
}

// NewImageSourcePollWithDefaults instantiates a new ImageSourcePoll object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageSourcePollWithDefaults() *ImageSourcePoll {
	this := ImageSourcePoll{}
	return &this
}

// GetIntervalSeconds returns the IntervalSeconds field value if set, zero value otherwise.
func (o *ImageSourcePoll) GetIntervalSeconds() int32 {
	if o == nil || IsNil(o.IntervalSeconds) {
		var ret int32
		return ret
	}
	return *o.IntervalSeconds
}

// GetIntervalSecondsOk returns a tuple with the IntervalSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourcePoll) GetIntervalSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.IntervalSeconds) {
		return nil, false
	}
	return o.IntervalSeconds, true
}

// HasIntervalSeconds returns a boolean if a field has been set.
func (o *ImageSourcePoll) HasIntervalSeconds() bool {
	if o != nil && !IsNil(o.IntervalSeconds) {
		return true
	}

	return false
}

// SetIntervalSeconds gets a reference to the given int32 and assigns it to the IntervalSeconds field.
func (o *ImageSourcePoll) SetIntervalSeconds(v int32) {
	o.IntervalSeconds = &v
}

// GetIntervalSecondsAfterWebhook returns the IntervalSecondsAfterWebhook field value if set, zero value otherwise.
func (o *ImageSourcePoll) GetIntervalSecondsAfterWebhook() int32 {
	if o == nil || IsNil(o.IntervalSecondsAfterWebhook) {
		var ret int32
		return ret
	}
	return *o.IntervalSecondsAfterWebhook
}

// GetIntervalSecondsAfterWebhookOk returns a tuple with the IntervalSecondsAfterWebhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourcePoll) GetIntervalSecondsAfterWebhookOk() (*int32, bool) {
	if o == nil || IsNil(o.IntervalSecondsAfterWebhook) {
		return nil, false
	}
	return o.IntervalSecondsAfterWebhook, true
}

// HasIntervalSecondsAfterWebhook returns a boolean if a field has been set.
func (o *ImageSourcePoll) HasIntervalSecondsAfterWebhook() bool {
	if o != nil && !IsNil(o.IntervalSecondsAfterWebhook) {
		return true
	}

	return false
}

// SetIntervalSecondsAfterWebhook gets a reference to the given int32 and assigns it to the IntervalSecondsAfterWebhook field.
func (o *ImageSourcePoll) SetIntervalSecondsAfterWebhook(v int32) {
	o.IntervalSecondsAfterWebhook = &v
}

// GetWebhookFreshnessSeconds returns the WebhookFreshnessSeconds field value if set, zero value otherwise.
func (o *ImageSourcePoll) GetWebhookFreshnessSeconds() int32 {
	if o == nil || IsNil(o.WebhookFreshnessSeconds) {
		var ret int32
		return ret
	}
	return *o.WebhookFreshnessSeconds
}

// GetWebhookFreshnessSecondsOk returns a tuple with the WebhookFreshnessSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSourcePoll) GetWebhookFreshnessSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.WebhookFreshnessSeconds) {
		return nil, false
	}
	return o.WebhookFreshnessSeconds, true
}

// HasWebhookFreshnessSeconds returns a boolean if a field has been set.
func (o *ImageSourcePoll) HasWebhookFreshnessSeconds() bool {
	if o != nil && !IsNil(o.WebhookFreshnessSeconds) {
		return true
	}

	return false
}

// SetWebhookFreshnessSeconds gets a reference to the given int32 and assigns it to the WebhookFreshnessSeconds field.
func (o *ImageSourcePoll) SetWebhookFreshnessSeconds(v int32) {
	o.WebhookFreshnessSeconds = &v
}

func (o ImageSourcePoll) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageSourcePoll) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IntervalSeconds) {
		toSerialize["intervalSeconds"] = o.IntervalSeconds
	}
	if !IsNil(o.IntervalSecondsAfterWebhook) {
		toSerialize["intervalSecondsAfterWebhook"] = o.IntervalSecondsAfterWebhook
	}
	if !IsNil(o.WebhookFreshnessSeconds) {
		toSerialize["webhookFreshnessSeconds"] = o.WebhookFreshnessSeconds
	}
	return toSerialize, nil
}

type NullableImageSourcePoll struct {
	value *ImageSourcePoll
	isSet bool
}

func (v NullableImageSourcePoll) Get() *ImageSourcePoll {
	return v.value
}

func (v *NullableImageSourcePoll) Set(val *ImageSourcePoll) {
	v.value = val
	v.isSet = true
}

func (v NullableImageSourcePoll) IsSet() bool {
	return v.isSet
}

func (v *NullableImageSourcePoll) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageSourcePoll(val *ImageSourcePoll) *NullableImageSourcePoll {
	return &NullableImageSourcePoll{value: val, isSet: true}
}

func (v NullableImageSourcePoll) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageSourcePoll) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
