spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/appbahn}
    username: ${DATABASE_USERNAME:appbahn}
    password: ${DATABASE_PASSWORD:appbahn}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
