apiVersion: v1
kind: Service
metadata:
  name: {{ include "appbahn.fullname" . }}-webhook
  labels:
    {{- include "appbahn.operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "appbahn.operator.selectorLabels" . | nindent 4 }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "appbahn.fullname" . }}-webhook-selfsign
  labels:
    {{- include "appbahn.operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "appbahn.fullname" . }}-webhook-cert
  labels:
    {{- include "appbahn.operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "appbahn.fullname" . }}-webhook-tls
  issuerRef:
    name: {{ include "appbahn.fullname" . }}-webhook-selfsign
    kind: Issuer
  dnsNames:
    - {{ include "appbahn.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "appbahn.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "appbahn.fullname" . }}-resource-validator
  labels:
    {{- include "appbahn.operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "appbahn.fullname" . }}-webhook-cert
webhooks:
  - name: resource-validator.appbahn.eu
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "appbahn.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-appbahn-eu-v1-resource
        port: 443
    rules:
      - apiGroups: ["appbahn.eu"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["resources"]
        scope: Namespaced
    matchPolicy: Equivalent
    timeoutSeconds: 10
