package eu.appbahn.platform.api;

import io.swagger.v3.oas.annotations.media.Schema;

/** Discrete platform mutation recorded in the audit log. */
@Schema(name = "AuditAction", enumAsRef = true)
public enum AuditAction {
    DEPLOYMENT_TRIGGERED,
    ENVIRONMENT_APPROVAL_GATES_UPDATED,
    ENVIRONMENT_CREATED,
    ENVIRONMENT_DELETED,
    ENVIRONMENT_QUOTA_UPDATED,
    ENVIRONMENT_REGISTRY_UPDATED,
    ENVIRONMENT_ROLE_OVERRIDE_REMOVED,
    ENVIRONMENT_ROLE_OVERRIDE_SET,
    ENVIRONMENT_TARGET_CLUSTER_UPDATED,
    ENVIRONMENT_TOKEN_CREATED,
    ENVIRONMENT_TOKEN_DELETED,
    ENVIRONMENT_UPDATED,
    GROUP_MAPPING_CREATED,
    GROUP_MAPPING_DELETED,
    GROUP_MAPPING_UPDATED,
    MEMBER_ADDED,
    MEMBER_INVITED,
    MEMBER_REMOVED,
    MEMBER_UPDATED,
    PROJECT_CREATED,
    PROJECT_DELETED,
    PROJECT_QUOTA_UPDATED,
    PROJECT_REGISTRY_UPDATED,
    PROJECT_ROLE_OVERRIDE_REMOVED,
    PROJECT_ROLE_OVERRIDE_SET,
    PROJECT_UPDATED,
    RESOURCE_CREATED,
    RESOURCE_DELETED,
    RESOURCE_RESTARTED,
    RESOURCE_STARTED,
    RESOURCE_STOPPED,
    RESOURCE_UPDATED,
    WORKSPACE_CREATED,
    WORKSPACE_DELETED,
    WORKSPACE_QUOTA_UPDATED,
    WORKSPACE_REGISTRY_UPDATED,
    WORKSPACE_SECURITY_UPDATED,
    WORKSPACE_UPDATED
}
